### ISSUE TITLE
Support of AJAX delete of resources.

### ISSUE THREAD

**Issue by romul** [smpallen99/ex_admin#105]
Provide possibility to delete resources without page reloading.
Related to #86

**Comment by smpallen99** [comment]
@romul Just started with wiki. Fell free to update 👍

**Comment by romul** [comment]
@smpallen99 Awesome!

**Comment by smpallen99** [comment]
@romul How do you feel about sharing a demo app for these features you are writing. I could put it up on exadmin.info along with the two I have up there right now. Either that, or you add to one of the two demo's i have up there already. 

To be honest, I'm very interested in the work your doing with many-to-many relationships. I've been struggling with the repo and changeset refactoring that uses the power of associations in Ecto.

**Comment by romul** [comment]
@smpallen99 Actually it will be shared at https://github.com/romul/synergy 
It will be something like a universal admin panel for e-commerce projects in the future. 
Atm it's very fluid b/c work on new features for ex_admin is in progress. But after pulling these features to ex_admin master, there will be no problem in working example.

**Comment by romul** [comment]
@smpallen99 Btw, is there a way to use `actions` macro inside `table_for`?
