### ISSUE TITLE
Customization of Columns

### ISSUE THREAD

**Issue by bsidoruk** [smpallen99/ex_admin#106]
I'm trying to add custom content to one of my columns on the index page
    
    column "Hits", &(length(&1.hits))
    
While it creates the column, the contents come back empty.  I also tried this with a row on a show page, and after tracing it through the ex-admin code,  it seems to get lost when it calls the markup :nested macro on the result of the function.
[https://github.com/smpallen99/xain/blob/master/lib/xain.ex#L118](url)
I got stuck at this point because I'm not overly familiar with the macros part of Elixir.  Hoping you could shed some light on this. Thanks

**Comment by smpallen99** [comment]
try 
```
column "Hits", &(text length(&1.hits))
```

**Comment by bsidoruk** [comment]
Thats worked. Thank you

**Comment by smpallen99** [comment]
Awesome!
