### ISSUE TITLE
Managing many-to-many relationships

### ISSUE THREAD

**Issue by jwarlander** [smpallen99/ex_admin#109]
ExAdmin looks pretty awesome, and I'd love for us to be able to use it as the main UI for a very data-centric web application that's just used for managing metadata.

However, is it currently possible to have eg. a BookLabels form (modelling a many-to-many relationship between Books and Labels) optionally create new Book entries, but just select existing Labels?

**Comment by jwarlander** [comment]
I'm of course happy to help if there's something that's missing for this to work, but I've only had a very cursory look at the ExAdmin source code so far..

Mainly got excited by the possibility of replacing the bare-bones UI generated by Phoenix with something that looks a lot nicer, and seems to require less boilerplate code / templating ;)

**Comment by smpallen99** [comment]
@jwarlander I presume your looking for something like a tags input box and when you type tags in that box, it will attach existing tags (many-to-many), or create new tags if they are not found. Probably all AJAX driven. Correct?

If that is what you are looking for, I can say that I have not built that yet. 

I'm just about to merge a large PR from @romul that has some cool many-to-many AJAX support. I think we can build on some of that code.

**Comment by jwarlander** [comment]
That's actually a nice idea too, especially if there would be some kind of autocompletion for the tags.. We've used checkboxes so far though, as our set of tags rarely changes. 

More importantly, I'd like for it to be possible to enter new titles / descriptions for books, in the above case, and have them created, while the tags can be selected from the pre-existing set.

I'm definitely going to take a close look at the new changes coming in, and go through the demo app in more detail :-)

**Comment by smpallen99** [comment]
the has_many macro allows you to create new ones, but does not allow you to select from existing. So, I think we could build on that.

**Comment by romul** [comment]
>  in the above case, and have them created, while the tags can be selected from the pre-existing set.

@jwarlander Most likely this will be possible with ex_admin at the next week.
I'm already working on this feature. And it will be something like an input field with autocomplete bellow table with already selected "tags" on the "book" show page.

**Comment by smpallen99** [comment]
@romul rocks!! 👍

**Comment by jwarlander** [comment]
Great news! :) Let me know if you need any help w/ testing along the way.

**Comment by romul** [comment]
@jwarlander There is a minor subtask that could be delegated if you'd like to participate: https://github.com/smpallen99/ex_admin/issues/112

**Comment by romul** [comment]
@smpallen99 
Working prototype is done. Please, review it.
Current syntax:
``` elixir
panel "Properties" do
  sortable_table_for(category, :category_properties) do
    column :property
    column :required, toggle: true
    column :displayable, toggle: true
  end

  markup_contents do
    association_filler(category, resource_key: "category_id", assoc_name: "properties", assoc_key: "property_id")
  end
end
```

And looks like:
![](https://api.monosnap.com/rpc/file/download?id=LaaUnfGaQ8ntRK812P9UlrfeCiXcU4)

I'm not sure about `association_filler` name for this macro.. maybe you have better suggestions.
P.S. I'm thinking about `autocomplete: false` option to be able preload list of all entries. It would be better in case when you have less than 100 `tags`, `labels`, etc.

**Comment by smpallen99** [comment]
Thanks @romul I'll pull down your branch this evening and try it out. I should have some feedback then. One thing I noticed is that you require to use to specify relationship information that we can probably get from `__schema__/2`. Not 100% sure, but will look at that when I'm testing it.

**Comment by romul** [comment]
@smpallen99 I've added a separate version of this macro with retrieving some info from `__schema__`, but it's not general: https://github.com/romul/ex_admin/blob/e634877a31800c40293cbf45c0aacfa4db0690d6/lib/ex_admin/show.ex#L271..L283

**Comment by romul** [comment]
Should to mention: it requires you to define 2 function inside association Ecto model, for example

``` elixir
  def admin_search_query(keywords) do
    from(p in Synergy.Property, where: ilike(p.name, ^("%#{keywords}%")), order_by: [:name])
  end

  def pretty_name(property) do
    property.name
  end
```
