### ISSUE TITLE
Admin Auth implementation, undefined function session_path

### ISSUE THREAD

**Issue by loongmxbt** [smpallen99/ex_admin#117]
I use Addict for auth, and follow the wiki to implement admin auth.
``` elixir
defimpl ExAdmin.Authentication, for: Plug.Conn do
  alias MyApp.Router.Helpers
  alias MyApp.Authentication, as: Auth

  def use_authentication?(_), do: true
  def current_user(conn), do: Auth.current_user(conn)
  def current_user_name(conn), do: Auth.current_user(conn).name
  def session_path(conn, action), do: Helpers.session_path(conn, action)
end

defmodule MyApp.Authentication do
  def current_user(conn) do
    Addict.Helper.current_user(conn)
  end
end
```

But it has error and says 
```
undefined function MyApp.Router.Helpers.session_path/2
```

and I find the phoenix/plug_auth docs/api, can't find something like `Router.Helpers.session_path`.
I checked the contact_demo, can't find a place `session_path` is defined.

I'm really new to Elixir and Phoenix, where did it go wrong? Thanks!

**Comment by smpallen99** [comment]
If this is the exact file you are using, can I presume your project is called `MyApp`? If it isn't, then you need to replace the instances of `MyApp` with the name of your project. Secondly, you need to add a route in your project for session so MyApp.Router.Helpers.session_path is created. 

You can review this file [router.ex](https://github.com/smpallen99/contact_demo/blob/master/web/router.ex) for a working example. 

I have not used Addict yet. There could still be an issue with the actions.

Let me know if this helps...

**Comment by smpallen99** [comment]
@loongmxbt Just to further explain... %MyApp%.Router.Helpers is automatically generated when your `web/router.ex` file is compiled. If you look at `web/web.ex`, you will see that its imported for `controller` and `view`.

**Comment by loongmxbt** [comment]
Thanks a lot, I understand it! `session` is a resource, and if I define route with SessionController, phoenix magically gives me a `session_path`.

``` elixir
def session_path(conn, action), do: Helpers.session_path(conn, action)
```
But in Addict, the session action is defined as modules like `Addict.Interactors.DestroySession` and `Addict.Interactors.CreateSession`

``` elixir
defmodule Addict.Interactors.CreateSession do
  import Plug.Conn

  @doc """
  Adds `user` as `:current_user` to the session in `conn`
  Returns `{:ok, conn}`
  """
  def call(conn, user, schema \\ Addict.Configs.user_schema) do
    conn = conn
    |> fetch_session
    |> put_session(:current_user, Addict.Presenter.strip_all(user, schema))
    {:ok, conn}
  end
end
```

So it seems a little hard to integrate with Addict, because the call() requires user and schema. session_path(conn, action) only gives conn and action.

**Comment by smpallen99** [comment]
I’ll take a look at Addict and see what it will take to get a successful integration….

**Comment by loongmxbt** [comment]
I've tried passport, which is a typical user auth lib includes session_controller, and find the `current_user` definition

https://github.com/opendrops/passport/blob/608b6f1e7eee00e5a92c38fd6dafaa3d41900fbf/lib/passport/plug.ex

``` elixir
defmodule Passport.Plug do
  import Plug.Conn

  @resource Application.get_env(:passport, :resource)
  @repo Application.get_env(:passport, :repo)

  def current_user(conn, _) do
    user_id = get_session(conn, :user_id)
    user = user_id && @repo.get(@resource, user_id)
    assign(conn, :current_user, user)
  end
end
```

``` elixir
defimpl ExAdmin.Authentication, for: Plug.Conn do
  alias HelloPassport.Router.Helpers
  alias HelloPassport.Authentication, as: Auth

  def use_authentication?(_), do: true
  def current_user(conn), do: Auth.current_user(conn)
  def current_user_name(conn), do: Auth.current_user(conn).email
  def session_path(conn, action), do: Helpers.session_path(conn, action)
end

defmodule HelloPassport.Authentication do
  def current_user(conn) do
    what_to_write_here
  end
end
```

In passport, I can use `@current_user.email` in templates, and find something like `Passport.plug.current_user(conn)` but didn't work. Wish help! Thanks a lot!

**Comment by smpallen99** [comment]
I just tired Addict. Reported two issues and submitted a PR for one. But I still can't figure out how to use it on a simple project without ExAdmin. I'll look at passport now. I hope I have better luck.

**Comment by loongmxbt** [comment]
@smpallen99 Awesome! Thanks a lot! The `forget pass` and `reset pass` of Passport seems not implemented right now. But it's more customizable than Addict.

**Comment by smpallen99** [comment]
I'm not having luck with Passport either. Not sure how to get protect a page, forcing it to authenticate. But to answer your question above, try this:
```
defmodule HelloPassport.Authentication do
  def current_user(conn) do
    conn.assigns[:current_user]
  end
end
```

**Comment by smpallen99** [comment]
Ok, I kind of have it working. The main issue I have right now is redirecting a user that is not logged in to the login page. It is unclear how this is supposed to be done with Passport. I was able to login, the go to my admin pages. The user name was displayed and I was able to logout. But the redirect after the logout field because I don't have a plug to redirect when you are not logged in.

To get what I described to work, you need to do a few things:

* change the `SessionController.delete` action to `destroy` like this.
```
  def destroy(conn, _) do
    conn
    |> Session.logout()
    |> put_flash(:info, "You have been logged out")
    |> redirect(to: session_path(conn, :new))
  end
```

Change the logout actions in the `web/router.ex` file to this:
```
    patch "/logout", SessionController, :destroy
    delete "/logout", SessionController, :destroy
```

And use the above in your auth module
```
defmodule HelloPassport.Authentication do
  def current_user(conn) do
    conn.assigns[:current_user]
  end
end
```

I'm going to review my use of destroy and change it.
Steve

**Comment by loongmxbt** [comment]
Got that! I need to define `action :destroy`, pretty same as `delete` for ExAdmin for now.

**Comment by smpallen99** [comment]
@loongmxbt I appreciate you brining this up as I've only tested with my own version of `Plug.Auth`. At this point, I'm not sure I've fully tested solution with Passport. So, I'm going to leave it open until I'm happy with it and have some documentation. 

BTW, do you have your admin pages requiring authentication before they can be accessed? If so, how to you check if the user is logged in and redirect them to the login page if they aren't?

**Comment by loongmxbt** [comment]
Sorry for close the issue. Really appreciate you reopen it for more improvements!

Because addict doesn't have session controller, and passport more like a basic `UserController` and `SessionController`, so I switch back to implement my own user auth. Pretty same as `Passport`. But more customizable with ExAdmin.

I now plug `auth_user`

``` elixir
  def auth_user(conn, _opts) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to access that page")
      |> redirect(to: Helpers.page_path(conn, :index))
      |> halt()
    end
  end
```
After when I have roles in my app, I gonna add `auth_admin`:
``` elixir
  def auth_admin(conn, _opts) do
    user = conn.assigns.current_user
    # find user role
    if user.role == :admin do
      conn
    else
      conn
      |> put_flash(:error, "Admin previledge required")
      |> redirect(to: Helpers.page_path(conn, :index))
      |> halt()
    end
  end
```

Here my use case is ExAdmin only allows user with admin role to login. 
``` elixir
Admin -> ExAdmin pipe_through [:browser, :auth_user, :auth_admin]
User -> Post Create  [:browser, :auth_user]
Public -> Post index and show [:browser]
```

Because now ExAdmin does not support for "user with specific role can see/edit specific model", so I want to make ExAdmin to the admin only the keep the app safe.

**Comment by OvermindDL1** [comment]
For note, if anyone needs an auth solution that does work with ex_admin, ueberauth and guardian work perfectly with ex_admin.

**Comment by smpallen99** [comment]
Good to hear!

**Comment by alkalinecoffee** [comment]
@OvermindDL1 would you mind posting a gist of your exadmin/guardian setup?

**Comment by OvermindDL1** [comment]
I just have the normal guardian plugs injected into the ex_admin plug path, nothing really special.

I also have my own permission system which is also injected into the plug path to do some more fine-grained tests.  You can do pretty much whatever you want with your own plug.

**Comment by ifree321** [comment]
@alkalinecoffee  When I add 
```elixir
def session_path(conn, :destroy), do: Helpers.session_path(conn, :delete, 0)
 ```
to my ```authentiation.ex``` file,I got the following error:
```
[error] #PID<0.465.0> running UserclientDemoWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for 0. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Scrivener.Page, Stream, Timex.Interval
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1850: Enum.reduce/3
        (userclient_demo) lib/userclient_demo_web/router.ex:1: UserclientDemoWeb.Router.Helpers.segments/3
        (userclient_demo) lib/userclient_demo_web/router.ex:1: UserclientDemoWeb.Router.Helpers.session_path/3
        (ex_admin) web/templates/themes/admin_lte2/layout/header.html.eex:25: ExAdmin.AdminLte2.LayoutView."header.html"/1
        (ex_admin) web/templates/layout/admin_lte2.html.eex:41: ExAdmin.LayoutView."admin_lte2.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (userclient_demo) lib/userclient_demo_web/endpoint.ex:1: UserclientDemoWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (userclient_demo) lib/userclient_demo_web/endpoint.ex:1: UserclientDemoWeb.Endpoint.plug_builder_call/2
        (userclient_demo) lib/plug/debugger.ex:99: UserclientDemoWeb.Endpoint."call (overridable 3)"/2
        (userclient_demo) lib/userclient_demo_web/endpoint.ex:1: UserclientDemoWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/lymin/elixir/UserClientDemo/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```
So I turned it into this：
```elixir
def session_path(conn, :destroy), do: Helpers.session_path(conn, :delete,[0])
```
everything renturned to normal。🙂
