### ISSUE TITLE
Support for Array type

### ISSUE THREAD

**Issue by loongmxbt** [smpallen99/ex_admin#118]
In https://hexdocs.pm/phoenix/Mix.Tasks.Phoenix.Gen.Model.html
There is `mix phoenix.gen.model User users nicknames:array:string`

But support for array:string or array:int seem to have error in ExAdmin admin model create resource.

Here my use case is something like `tags:array:string` or `locations:array:string`.

Is Array the right type use here?

If so, is there any support for something like tags input Array type? Like this one:
 https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

Thanks a lot!

**Comment by smpallen99** [comment]
We have not added support for the array type yet. To get your nicknames example working, you could use a Nicknames schema with a belongs_to to User.

For the tagging example, Issue #109 is addressing some of what you will need if you use a join table and has_many :through. 

The bootstrap plugin looks kewl, I’ll look into it more.

**Comment by romul** [comment]
@smpallen99 We already have https://select2.github.io/examples.html#tags 
So I'm not sure that the additional plugin is necessary.

**Comment by loongmxbt** [comment]
Yeah, I just use `bootstrap-tagsinput` as an example, the plugin by default used in AdminLTE theme is `select2`.
```
v2.2.0:

Bug fixes
Added support for Select2
Updated ChartJS
```

**Comment by OvermindDL1** [comment]
How is the array type going?  I currently have a `{:array, :map}` type that is the basis of the main schema so need both array and map support.

**Comment by smpallen99** [comment]
Its not going yet. Been swamped on a ExAdmin based project that required some new features and refactoring. Can’t commit to when I’ll get a chance to look at this. I might be able to look at it on the weekend or next week.

Steve

**Comment by smpallen99** [comment]
support for :map and {:array, :map} done.
