### ISSUE TITLE
Suggestion: React instead of jQuery

### ISSUE THREAD

**Issue by cpursley** [smpallen99/ex_admin#120]
Suggestion. Keeping the JS side as functional and maintainable as possible would be nice. It looks like much of this project could be utilized: https://github.com/booleanhunter/ReactJS-AdminLTE

**Comment by smpallen99** [comment]
An interesting idea. It would probably not be me doing it. I have no experience with ReactJS and not really any time to learn it. The JS that comes wth AdminLTE seems to be working pretty well for what we need at this point. Perhaps if we find ourselves doing a lot of JS programming then I might be a little more motivated :)

I'm always open to looking at a prototype 👍 

Thanks for your suggestion.

**Comment by loongmxbt** [comment]
I think in backend ExAdmin does not need to integrate React, it only does some CRUD and displays data. Not really that much interactive components need the correct component lifecycle and one-way flow data(Flux).

In the frontend we can use React+Redux+Webpack to build some SPA using Phoenix API and data sources, keep the app nice, testable and maintainable.

**Comment by smpallen99** [comment]
testable and maintainable 👍
