### ISSUE TITLE
Support an after callback on the controller

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#123]
I have the need to post process a newly created or updated resource. So, I'm going to add an after callback to the controller.

**Comment by romul** [comment]
@smpallen99 Oops, these major changes in AdminController make rebase of #115 too complicated.
Could we revert this commit and reapply it after merge of #115?

**Comment by smpallen99** [comment]
Roman,

Just made you a contributor. Hope you don’t mind. That way, if I get hit by a bus… :)

Lets continue with the pull request process for normal commits. In this case, you welcome to revert, commit, and reapply.  

Steve

**Comment by romul** [comment]
Thank you, Steve. I appreciate it :-)
I will reapply `after_filter` changes soon.
