### ISSUE TITLE
sort_handle_column is not working

### ISSUE THREAD

**Issue by romul** [smpallen99/ex_admin#128]
That's because column with fun renders content outside of table like it was in https://github.com/smpallen99/ex_admin/issues/41
```
table_for(category.category_properties) do
  column "", [], fn(_) ->
    i "", class: "fa fa-bars handle", "aria-hidden": "true"
  end
  column :displyable
end
```

**Comment by romul** [comment]
Looks like it is Xain related issue, b/c `Xain.i` returns `:ok` instead of content.

**Comment by romul** [comment]
Well, I found. It was broken by https://github.com/smpallen99/ex_admin/pull/116/commits/cae5749ad19b3a7259976f1df59005a1f1b6768c

**Comment by smpallen99** [comment]
Yes, I was a little worried about that change, but seemed like the right thing to do. It was a but that was introduced with the theme support I think. I worked around it by forcing them to something like `row “Name”, &(text &1.full_name)` instead of the documented `row “Name”, &(&1.full_name)`. 

Is this casing big issues for you?

**Comment by smpallen99** [comment]
Yes, Xain.tag does not return the contents, only the rendered html. I spent a few hours the other day trying to fix that without any success and gave up.

**Comment by romul** [comment]
@smpallen99 Atm it renders like:
![](https://api.monosnap.com/rpc/file/download?id=uP6gY0tySl72ka6h1bbKMyvXqyHY8N)

I guess, correct solution would be add case clause instead of replacing
```elixir 
for field <- columns do
  case field do
    {f_name, %{fun: fun}} when is_function(fun) ->
      td ".td-#{parameterize f_name} #{fun.(resource)}"
    {f_name, fun} when is_function(fun) ->
      td ".td-#{parameterize f_name} #{fun.(resource)}"
    {f_name, opts} ->
      build_field(resource, conn, {f_name, Enum.into(opts, %{})}, fn(contents, f_name) ->
        td ".td-#{parameterize f_name} #{contents}"
      end)
  end
end
```

**Comment by romul** [comment]
@smpallen99 Ignore previous message.. adding clause is not working as well.
I'm going to revert #116 and fix it in other way.

**Comment by romul** [comment]
Fixed.
