### ISSUE TITLE
AdminLTE Navbar

### ISSUE THREAD

**Issue by cpursley** [smpallen99/ex_admin#131]
[AdminLTE top-nav](https://almsaeedstudio.com/themes/AdminLTE/pages/layout/top-nav.html) as a configuration option would be handy. Something like:

```
config :ex_admin,
  skin_color: :purple,
  navbar: :top
```

**Comment by smpallen99** [comment]
I started doing a top nav template, but decided to focus on the side nav template. This is why the existing template is called AdminLTE2 :). 

It should be pretty straight forward to add a new theme with top nav. Just might need to play around with sharing code between the to AdminLTE themes. 

Is this something you would like to contribute?

**Comment by cpursley** [comment]
Thanks. I may take a stab at this. Closing as per new contributor guide.
