### ISSUE TITLE
Override attributes_table?

### ISSUE THREAD

**Issue by cpursley** [smpallen99/ex_admin#132]
Is there a way to override an `attributes_table` and reference a PhoenixView similar to a sidebar?

**Comment by smpallen99** [comment]
The following should work (have not tested it). 

```elixir
panel "ExAdmin Demo" do
  markup_contents do
    Phoenix.View.render(ExAdminDemo.AdminView, "sidebar_links.html", [model: "dashboard"])
    |> Phoenix.HTML.safe_to_string
    |> raw
  end
end
```
and just don’t use the `attributes_table` macro.

The page code shares a lot of the show code and the above it taken from the following working example:
https://github.com/smpallen99/ex_admin_demo/blob/master/web/admin/dashboard.ex#L81 <https://github.com/smpallen99/ex_admin_demo/blob/master/web/admin/dashboard.ex#L81>

Let me know if it works.

**Comment by cpursley** [comment]
Thanks, works perfectly. Would you like me to add instructions for this and sidebars to the wiki?

**Comment by smpallen99** [comment]
Would love that. Thanks!!

**Comment by romul** [comment]
I've added an example to wiki: https://github.com/smpallen99/ex_admin/wiki/How-to-use-a-custom-template-for-the-dashboard
