### ISSUE TITLE
Content is not rendered when it includes new lines

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#133]
Under some situations, which I have not yet qualified, do not render the contents when it includes new line characters. I have not found out where this is happening and have included several work arounds 👎  to do a `String.replace contents, "\n", ""` to get around the issue. This needs to be fixed.

**Comment by romul** [comment]
@smpallen99 Could you add some examples?

**Comment by smpallen99** [comment]
Sure. if you remove this line https://github.com/smpallen99/ex_admin/blob/master/lib/ex_admin/table.ex#L86 and then view the dashboard page in [ExAdminDemo](https://github.com/smpallen99/ex_admin_demo), you will see that the last panel does not have any text.

I thought it might be related to `markup :nested do` but tested Xain directly. We are getting the correct text back from Xain as confirmed with a  `pry`, but its getting stripped out somewhere laster.

**Comment by smpallen99** [comment]
I also has the same issue with this code until I added the String.replace at the end.

```elixir
    show license do
      panel "License Key"  do
        markup_contents do
          div ".form-group" do
            div ".input-group" do
              Xain.input "#key.form-control", value: license.license
              div ".input-group-addon" do
                span ".input-group-button", "data-toggle": "tooltip", title: "Copy to clipboard" do
                  button ".btn.btnn", type: "button", "data-clipboard-target": "#key", "data-toggle": "copied", title: "Copied!" do
                    img ".clippy", src: "/images/clippy.svg", width: "13", alt: "Copy to clipboard"
                  end
                end
              end
            end
          end
          script("""
              $(function() {
                var clipboard = new Clipboard('.btnn');
                clipboard.on('success', function(e) {
                  $("[data-toggle='tooltip']").tooltip('hide');
                  ...
              });
          """
          |> String.replace("\n", ""))
        end
    ...
```

**Comment by romul** [comment]
Hmm, I tried to call `panel` macro and other macros from iex, but they have so many external dependencies.. So I guess macros rendering is another target for decoupling and refactoring :-)

**Comment by smpallen99** [comment]
Controller test on dashboard should do the trick

**Comment by romul** [comment]
@smpallen99 Controller tests in Phoenix belong to integration testing. So, it's not the best choice to test internals.

**Comment by romul** [comment]
Minimal buggy code:
```elixir
Xain.markup do   
  Xain.p("""     
    line1
    line2
    line3
  """)
end
# => {:safe, "<p>  line1\n  </p>"}
```

**Comment by romul** [comment]
```elixir
str = """     
line1
line2
line3
"""
Xain.Helpers.id_and_class_shortcuts(str, [])
{"line1\n  ", []}
```

**Comment by romul** [comment]
Fixed in Xain: https://github.com/smpallen99/xain/pull/4/files
