### ISSUE TITLE
Add support for both Ecto 1.1 and 2.0 in same ExAdmin version

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#135]
Allow both versions of Ecto to work.

**Comment by smpallen99** [comment]
I have the feature pretty well complete with tests. Just need to add some instructions in read me for configuring deps for each version.

**Comment by smpallen99** [comment]
@romul We should now be able to develop everything on master. I've manually tested this with contacts_demo and it looks like it works fine. Let me know if you see any issues.

**Comment by romul** [comment]
@smpallen99 Wow, looks great! 
We should patch few lines in resource controller too.
https://github.com/smpallen99/ex_admin/blob/master/web/controllers/admin_resource_controller.ex#L207
https://github.com/smpallen99/ex_admin/blob/master/web/controllers/admin_resource_controller.ex#L226

**Comment by smpallen99** [comment]
Yes, I missed them. Will do after I get some lunch.

**Comment by smpallen99** [comment]
@romul Fixed. Thanks!
