### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by HangingClowns** [smpallen99/ex_admin#136]
Hi,

I'm looking forward to using this in an upcoming project, but need to support multiple languages. Is there a way to do this out of the box or would it require some work in the code? It seems the community is leaning towards gettext and po files.

**Comment by smpallen99** [comment]
I believe it will require a little work. Probably just the Action names, error messages, and the JS messages.

**Comment by HangingClowns** [comment]
Okay. Let me try and see.

**Comment by HangingClowns** [comment]
@smpallen99 can you assign to me?

**Comment by smpallen99** [comment]
@HangingClowns I believe I can only assign issues to core contributors. But no problem. I'll make sure now one tries to start it. I look forward to reviewing your pull request.
