### ISSUE TITLE
textarea usage

### ISSUE THREAD

**Issue by pollingj** [smpallen99/ex_admin#139]
There doesn't appear to be a way to get a textarea output.  I can see some code in the `form.ex` where there is a mention of :text however I don't see how that works.  Am I missing something here?  I'm using the latest version of Ecto 2 etc.

**Comment by romul** [comment]
@pollingj Thank you for the report. 
Please, try version in the master branch and specify form block like

``` elixir
  register_resource Example.Page do
    form page do
      inputs do
        input page, :title
        input page, :body, type: :text
      end
    end
  end
```
