### ISSUE TITLE
admin.html seems to be missing?

### ISSUE THREAD

**Issue by tmock12** [smpallen99/ex_admin#14]
Following the installation guides, I get the error message:
```
Could not render "admin.html" for ExAdmin.AdminView, please define a matching clause for render/2 or define a template at "web/templates/admin". No templates were compiled for this module.
```

Which I just happened to notice is the same message @smpallen99  got at ElixirConf. Do you know what would cause this and how I should fix it?
<img width="738" alt="screen shot 2015-10-20 at 2 41 05 pm" src="https://cloud.githubusercontent.com/assets/1124585/10617445/a7b0e7ba-7738-11e5-9c85-ca1badd6afb4.png">

**Comment by smpallen99** [comment]
try `mix deps.compile` that just worked for me.

**Comment by tmock12** [comment]
Yay, that did it! I had run `mix do deps.get, compile` but looking at it now, it doesn't look like it runs the compile command. I've put in a PR to update the README.
