### ISSUE TITLE
Add support to override index page filter field labels

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#141]
I have an Account resource which I've labeled Customer on the menu and actions. I would like to also label this resource in the index page filters with the following syntax:

```elixir
    filter [:name, :description, :user, :account, labels: [account: "Customer"]]
```

**Comment by romul** [comment]
@smpallen99 Could be there more than one custom label? If so, maybe `labels:` would be better?

**Comment by smpallen99** [comment]
good point. I’ll change it.
