### ISSUE TITLE
Undefined Function Error when trying to add new model with Phoenix 1.1.6

### ISSUE THREAD

**Issue by HStromfelt** [smpallen99/ex_admin#143]
I have a fresh install of the Phoenix framework. I then followed the installation instructions for ExAdmin. The initial Dashboard page loads perfectly under /admin. However, when adding a new model using 
"mix admin.gen.resource Account" I get the following error when trying to run the server:

== Compilation error on file web/admin/account.ex ==
** (UndefinedFunctionError) undefined function DashboardPhoenix.ExAdmin.account/0 (module DashboardPhoenix.ExAdmin is not available)
    DashboardPhoenix.ExAdmin.account()
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:877: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
    (elixir) lib/kernel/parallel_compiler.ex:100 : anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

The config file looks like this:
config :ex_admin,
  repo: DashboardPhoenix.Repo,
  module: DashboardPhoenix,
  modules: [
    DashboardPhoenix.ExAdmin.Dashboard,
    DashboardPhoenix.ExAdmin.Account,
  ]

------------
I am using IEx 1.2.6, Mix 1.2.6 and Phoenix  1.1.6 

Have I missed something or is this a problem with using a newer Phoenix version or something like that?
I tried checking this by copying your mix.exs file from the demo version, but I eventually came to the same error.

Thanks

**Comment by smpallen99** [comment]
@HStormfelt. Can you post your DashboardPhoenix.ExAdmin.Account module please. Thanks

**Comment by HStromfelt** [comment]
Sure: 
defmodule DashboardPhoenix.ExAdmin.Account do
  use ExAdmin.Register

  register_resource DashboardPhoenix.Account do

  end
end

On a previous attempt I copied over the body from the dashboard.ex file, but at the moment I have left it untouched.

**Comment by smpallen99** [comment]
One more question. What version of ExAdmin?

**Comment by HStromfelt** [comment]
Sure, I am using 0.7.6. I included it with {:ex_admin, "~> 0.7"}

Thanks for the help

**Comment by smpallen99** [comment]
Doing a quick test. Just a minute

**Comment by smpallen99** [comment]
There does appear to be an issue. I got a different error thought. Looking into it now.

**Comment by smpallen99** [comment]
@HStromfelt Sorry, my mistake. I generated a resource for the incorrect model. Test project working fine on versions you mention above. So, must be a problem with your project. Can you show me your whole project either on github, or send me a tar file at smpallen99 at yahoo dot com

**Comment by HStromfelt** [comment]
Sorry for my delayed reply, back now!

Thanks checking it out. I'm using the Cloud 9 IDE and have followed this tutorial to get the set up done: https://medium.com/@Oxyrus/how-to-install-the-phoenix-framework-on-cloud9-ef0ac265229c#.a5o7e3anu so perhaps the problem originates somewhere in there!

I've put the project up on my github now (https://github.com/HStromfelt/Koaloo_elixir). Cheers for taking a look

**Comment by smpallen99** [comment]
@HStromfelt I don't see where you have programmed your model. If you run the following it should work:
```
mix phoenix.gen.model Account accounts name 
mix ecto.setup
``` 
Then it should work. Let me know...

In the mean time, I'll open an issue to improve the error message for this scenario.
Steve

**Comment by HStromfelt** [comment]
@smpallen99 That is great thank you, I should have realised. It did the trick. I am quite new to Elixir and Phoenix so I totally overlooked it. Thanks!

**Comment by smpallen99** [comment]
Glad you got it working.
