### ISSUE TITLE
Support more then 1 controller before_filter and 1 after_filter

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#145]
I would like to have a before_filter for :create and :update, and another for only :update. So, I would like to have define multiple before_filters in the do controller block.

**Comment by romul** [comment]
@smpallen99 Are you sure that `filters` is the best idea? Usually it results to complicated and tangled code. I would prefer an ability to override entire action if necessary.
Indeed it's already possible thanks to Phoenix router, but it could be improved to avoid actions code duplication.

**Comment by smpallen99** [comment]
Its done and I have a product in production using the feature. So, we can deprecate it the future if we find a better solution. With that said, I don’t see much difference between the before filters and plugs. Accept a conn and params, and turn conn and params. Furthermore, if we override complete action, then they are either going to have to duplicate the active admin action, or call it at the end of the override one.

**Comment by romul** [comment]
> if we override complete action, then they are either going to have to duplicate the active admin action

Yes, exactly! It's why these actions should be as simple as possible and be composed from helpful functions. My point - it's imminent need for complex cases. Attempts to avoid this complicate the simple cases. Therefore, I propose to think about how to provide the most convenient ability to overload actions.
For example, `create` action could look like:
``` elixir
  def create(conn, defn, resource, params) do
    model = defn.__struct__
    changeset = ExAdmin.Repo.changeset(model.changeset_fn, resource, params[defn.resource_name])

    case ExAdmin.Repo.insert(changeset) do
      {:error, changeset} ->
        handle_changeset_error(conn, changeset, params)
      resource ->
        conn
        |> handle_after_filters(:create)
        |> put_flash(:notice, "#{base_name model} was successfully created.")
        |> redirect(to: admin_resource_path(resource, :show))
    end
  end
```
