### ISSUE TITLE
How to import csv to restore data?

### ISSUE THREAD

**Issue by loongmxbt** [smpallen99/ex_admin#150]
In ExAdmin, there is a CSV output, where can I import the CSV to override/insert new data?

**Comment by loongmxbt** [comment]
The thing is related to how to insert bulk data with differnent format?
e.g. A tab seperate file
```
time	buy	sell
1	10	5
2	20	6
3	30	7
```
If I use Repo.insert, I need to change every line of data to Struct.
```
Repo.insert!(%Record{time: 1, buy: 10, sell: 5})
```
if there is string,I need to add " " around it.
For now, I use editor's "Colum Edit" to manually edit the file to insert code.
Is there any simple way to do that? Thanks!

**Comment by smpallen99** [comment]
We don't yet have a csv import feature supported in ex_admin. In the past, I have implemented csv import with the `csvlixir` package. You could use the `collection_action` macro in your resource file and then process the file with `CSVLixir.read`.

For your second question, you could so something like
```elixir
iex(3)> Enum.zip([:time, :buy, :sell], [1, 10, 5]) |> Enum.into(%{})
%{buy: 10, sell: 5, time: 1}
```

**Comment by loongmxbt** [comment]
Thanks a lot!

**Comment by loongmxbt** [comment]
``` elixir
iex(23)> data = ~w(1   10  5
...(23)> 2   20  6
...(23)> 3   30  7)
["1", "10", "5", "2", "20", "6", "3", "30", "7"]

data |> Enum.chunk(3)

key = ~w()
iex(25)> key = ~w(time buy sell)a
[:time, :buy, :sell]

for rec <- data do
    Enum.zip(key, rec) |> Enum.into(%Record{})
end

Repo.insert(%Record{})

If not using `Eunm.into` to transfer to Struct, can use insert_all in ecto2 [[key, val, key, val], [key, val, key, val]]

MyApp.Repo.insert_all(Post, [[title: "hello", body: "world"],
                             [title: "another", body: "post"]])

```
