### ISSUE TITLE
One-to-many bug, can't modify field via the dropdown list.

### ISSUE THREAD

**Issue by loongmxbt** [smpallen99/ex_admin#151]
Two models: `Company` and `CompanyType`, reference is `company_type_id`
```
  schema "companies" do
    field :name, :string
    field :province, :string
    field :city, :string
    field :capital, :string
    field :description, :string
    belongs_to :company_type, Elecity.CompanyType

    timestamps
  end
```

and

```
  schema "company_types" do
    field :name, :string
    field :description, :string

    timestamps
  end
```

```
defmodule Elecity.Repo.Migrations.AddCompanyTypeIdToCompany do
  use Ecto.Migration

  def change do
    alter table(:companies) do
      add :company_type_id, references(:company_types)
    end
  end
end
```

In ExAdmin backend, In `new company`
I can choose from the existing company types(a drop down list), but after creation, the company type field is empty. That is, I cannot modify the company_type through ExAdmin(dropdown list and create), but can modify through Repo.insert.

In `list company`, I can see the company type of data from seeds.exs, which has a company_type_id value.

Maybe something related to the `_`?

Something strange here, wish some help!

**Comment by smpallen99** [comment]
Typically this happens if you don’ have the company_type_id listed either the @required_fields or @optional_fields in your model.

**Comment by loongmxbt** [comment]
Solved, add company_type_id to optional_fields. Thanks!
