### ISSUE TITLE
Problems with has_many association

### ISSUE THREAD

**Issue by Moxide** [smpallen99/ex_admin#152]
Hello,
I'm using the latest Ecto 2 with the master of ex_admin.
While trying to customize a form to show a has-many relation, I faced some issues.

I have two models :
```
  schema "group" do
    field :nom, :string
    has_many :users, MyApp.User
  end

  schema "user" do
    field :nom, :string
    belongs_to :group, MyApp.Group
  end
```

I want to be able to choose users in the group edit form (using checkboxes)
So I wrote in web/admin/group.ex :
```
form group do
     inputs  do
       input group, :nom
       inputs :users, as: :check_boxes, collection: MyApp.User.all
     end
end
```
But it throws an exception about "MyApp.User.all" being undefined or private.
so I replaced with :
```
form group do
     inputs  do
       input group, :nom
       inputs :users, as: :check_boxes, collection: MyApp.Repo.all(MyApp.User)
     end
end
```
Then it throws 
```
** (KeyError) key :name not found in: %MyApp.User
lib/ex_admin/form.ex:754: anonymous fn/6 in ExAdmin.Form.build_item/5 
```
Debugging this led to line 752 of form.ex. I changed :
`theme_module(conn, Form).collection_check_box opt.name, name_str, opt_id, selected`
to 
`theme_module(conn, Form).collection_check_box opt.nom, name_str, opt_id, selected`
(the 'name' field is hardcoded)

Great, the list of users is now displaying as checkboxes.
But, when I try to check a few users and update the group, this error is raised :
```
** (UndefinedFunctionError) function :error.__struct__/0 is undefined (module :error is not available)
        :error.__struct__()
        ExAdmin.Repo.do_collection/2
        lib/ex_admin/repo.ex:184: anonymous fn/3 in ExAdmin.Repo.insert_or_update_collection/2
```

And here I'm stuck !
Are all those problems due to wrong elixir or erlang versions ? I'm using Erlang 19 and elixir 1.3.0.

Thanks for any insight you might give.

**Comment by smpallen99** [comment]
@Moxide Where is your problem description?

**Comment by Moxide** [comment]
I'm currently writing it, sorry I pressed return by mistake...

**Comment by smpallen99** [comment]
@Moxide I think you may be confusing has_many with many_to_many here. With the has_many relationship you defined in the models above, you can only have one group per user. So, trying to list groups a checkboxes does not make sense here. Radio buttons would make sense but does not really add any value over a select control. ExAdmin does not yet support radio buttons for has_many relationship. 

I just tested a new project (using current master, just updated an hour ago) using your schema above with default resource files (no manual editing) and they work just fine. 

If you really want to have a user belonging to more than one group, then you need to use a has_many, through: relationship with a join table (GroupsUsers for example). Note that ExAdmin does not yet support the :many_to_many schema keyword yet. You can see examples of this at [Contacts Live Demo](http://demo2.exadmin.info/admin) and view the source from the demo.

I will, however, look at the hardcoded :name field you pointed out above and make sure we don't have an issue with many_to_many associations.

Also, if you want to use syntax like MyProject.Group.all, then add the following to your `web/web.ex` file:

```elixir
  def model do
    quote do
      use Ecto.Schema
      # ...
      def all, do: MyProject.Repo.all(__MODULE__)
    end
  end
```
This will provide an all function for all your models/schemas.

Steve

**Comment by smpallen99** [comment]
There is a problem with many to many relationships with the code identified above when properly defining a many to many relationship. The problem can be reproduced with the following:

```elixir
 schema "group" do
    field :nom, :string
    has_many :groups_users, OverrideName.GroupUser
    has_many :users, through: [:groups_users, :user]
    timestamps
  end

  schema "user" do
    field :nom, :string
    has_many :groups_users, OverrideName.GroupUser
    has_many :groups, through: [:groups_users, :group]
    timestamps
  end

  schema "groups_users" do
    belongs_to :group, OverrideName.Group
    belongs_to :user, OverrideName.User
  end

defmodule OverrideName.ExAdmin.User do
  use ExAdmin.Register
  register_resource OverrideName.User do
    show user do
      attributes_table do
        row :nom
      end
      panel "Groups" do
        table_for user.groups do
          column :nom
        end
      end
    end
    form user do
      inputs do
        input user, :nom
      end
      inputs "Groups"  do
        inputs :groups, as: :check_boxes, collection: OverrideName.Group.all
      end
    end
    query do
      %{all: [preload: [:groups]]}
    end
  end
end
```

**Comment by Moxide** [comment]
Thank you very much for those insights !
Indeed I was using many_to_many keywords in my models, I guess the last error is due to this fact.

Concerning the hardcoded name, it's fixed by defining 'display_name' in my model. Except when not using checkboxes, but its fixed is the referenced PR ;-)

Thank you very much.
