### ISSUE TITLE
to_string on breadcrumb "name" causes exception with some kinds of data

### ISSUE THREAD

**Issue by adamkittelson** [smpallen99/ex_admin#154]
Hey thanks for creating this library, just started playing with it today to see if it can replace my hand-rolled super ugly admin interface.

In issue #35 String.to_integer was changed to to_string to prevent UUIDs from raising an exception. I ran into a similar issue this evening where to_string is also not lenient enough.

It looks like, in addition to the id column, breadcrumbs are using the value of the first available column (which the breadcrumb code refers to as name). For one of my models that happens to be a jsonb column, and the data that doesn't respond well to `to_string` is a list of maps.

For example in IEx:
```
iex(1)>  to_string([%{"foo" => "bar"}])

** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[%{"foo" => "bar"}]

    (elixir) lib/list.ex:624: List.to_string/1
```

So this causes me to get an error if I visit the ExAdmin /edit page for this item.

Changing the `to_string` on this line https://github.com/smpallen99/ex_admin/blob/4c079d955396c3a868e1d54739dc6ceab32a136f/lib/ex_admin/breadcrumb.ex#L39 to `inspect` would fix my error in the short term, longer term I'm not sure that grabbing a value from an arbitrary field is necessarily a good fit for the breadcrumb creation, but I don't have a super good alternate suggestion off the top of my head.

Thanks for looking into this!
Adam

**Comment by smpallen99** [comment]
With the following fix, you can resolve this issue by creating a display_name/1 function in either your model, or in the resource definition file. See the `test/support/schema.exs` and `test/breadcrumb_test.exs` files for more details. I also added support for models that use a different primary key (not :id).

**Comment by smpallen99** [comment]
@adamkittelson Thanks for detailed description of the issue. I hope this fix resolves your issue.

**Comment by adamkittelson** [comment]
@smpallen99 Perfect thanks, verified that the default behavior no longer crashes and was able to customize it via display_name/1. Thanks for the quick fix!
