### ISSUE TITLE
CSV insert_at/updated_at columns

### ISSUE THREAD

**Issue by dguillot** [smpallen99/ex_admin#159]
Downloading the CSV, the items are showing up but there's no time under "insert_at". I'm assuming that's the time that my item was added. After Editing one item, the updated_at column is not populated either.

Anyone see this too?

**Comment by smpallen99** [comment]
Will push a fix for this later today. Also, the csv do customization is not working. Will fix it too.

**Comment by smpallen99** [comment]
Fixed. Added few other csv related features
