### ISSUE TITLE
Could not render "admin.html"

### ISSUE THREAD

**Issue by tispratik** [smpallen99/ex_admin#16]
I am getting the below error 

Could not render "admin.html" for ExAdmin.AdminView, please define a matching clause for render/2 or define a template at "web/templates/admin". No templates were compiled for this module.
Assigns:

My env is:
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:comeonin, "~> 1.3"},
     {:ex_admin, github: "smpallen99/ex_admin"}]

Am not sure if its related to the latest Phoenix version.

**Comment by tispratik** [comment]
Seems like in the below method the put_layout is not loading the html "relative-ly"

```ruby
  defp set_layout(conn, _) do
    put_layout(conn, "admin.html")
    # put_layout(conn, {ExAdmin.LayoutView, "admin.html"})
  end
```

**Comment by smpallen99** [comment]
I believe you are experiencing issue #14. Try compiling yor deps with 'mix deps.compile'

**Comment by tispratik** [comment]
Still the same :(

```
$ mix deps.compile
==> fs (compile)
==> ranch (compile)
==> poolboy (compile)
cc -g -O3 -Wall -I/usr/local/Cellar/erlang/18.0.3/lib/erlang/erts-7.0.3/include -Ic_src -fPIC -shared -dynamiclib -undefined dynamic_lookup -o priv/bcrypt_nif.so c_src/bcrypt_nif.c c_src/blowfish.c
==> cowlib (compile)
==> cowboy (compile)
```

```
page_name: "Dashboard", plugs: [], title_actions: &ExAdmin.default_page_title_actions/2, type: :page}, filters: false, html: {:safe, "<div class=\"blank_slate_container\" id=\"dashboard_default_message\"><span class=\"blank_slate\"><span>Welcome to ExAdmin. This is the default dashboard page.</span><small>To add dashboard sections, checkout 'web/admin/dashboards.ex'</small></span></div>"}, resource: nil}

        web/views/admin_view.ex:4: ExAdmin.AdminView.template_not_found/2
        (phoenix) lib/phoenix/view.ex:197: Phoenix.View.render_within/3
        (phoenix) lib/phoenix/view.ex:341: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:628: Phoenix.Controller.do_render/4
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (myapp) lib/phoenix/router.ex:255: Myapp.Router.dispatch/2
        (myapp) web/router.ex:1: Myapp.Router.do_call/2
        (myapp) lib/myapp/endpoint.ex:1: Myapp.Endpoint.phoenix_pipeline/1
        (myapp) lib/plug/debugger.ex:90: Myapp.Endpoint."call (overridable 3)"/2
        (myapp) lib/phoenix/endpoint/render_errors.ex:34: Myapp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by smpallen99** [comment]
I just tried setting up a new project and had the same issue. After receiving the issue, I ran `mix deps.compile ex_admin` and started the phoenix server again. That fixed the issue.

Other things to look at:
* make sure you have your router.ex file setup and your config entry per the instructions printed when you run `mix admin.install`. For my Blog project, these instructions were:
```
Remember to update your config file:

    config :ex_admin,
      repo: Blog.Repo,
      module: Blog,
      modules: [
        Blog.ExAdmin.Dashboard,
      ]


Add the admin routes to your web/router.ex:

    use ExAdmin.Router
    admin_routes :admin

Add Scrivener paging to your Repo:

    defmodule Blog.Repo do
      use Ecto.Repo, otp_app: :blog
      use Scrivener, page_size: 10
    end
```

If this still does not work, can you push a sample project to github so I can take a look? 
Thanks,
Steve

**Comment by tispratik** [comment]
Hey @smpallen99,  Thank you very much for helping me out.
The repo is https://github.com/tispratik/helloelixir

One thing thats a little bit different in my app is having support for multiple sub-domains.
So, to visit admin page, i visit mydomain.com/admin while the subdomains being foo.mydomain.com and bar.mydomain.com

But i have tested against that and it does not seem to be affecting the issue.

**Comment by smpallen99** [comment]
I pushed a couple updates earlier that removes the dependency on haml for ex_admin. I believe this was causing the need for recompiling the ex_admin dep after running `mix admin.install`. 

I have @tispratik helloelixir project working now. Here are the diffs from the working project:

```
diff --git a/config/config.exs b/config/config.exs
index 91eeff2..12d9105 100644
--- a/config/config.exs
+++ b/config/config.exs
@@ -18,7 +18,13 @@ config :myapp, Myapp.Endpoint,
 config :logger, :console,
   format: "$time $metadata[$level] $message\n",
   metadata: [:request_id]
-
+
+config :ex_admin,
+      repo: Myapp.Repo,
+      module: Myapp,
+      modules: [
+        Myapp.ExAdmin.Dashboard,
+      ]
 # config :phoenix, :template_engines,
 #  haml: PhoenixHaml.Engine

diff --git a/mix.exs b/mix.exs
index 544ce21..2bfe1a6 100644
--- a/mix.exs
+++ b/mix.exs

@@ -32,10 +32,11 @@ defmodule Myapp.Mixfile do
   defp deps do
     [{:phoenix, "~> 1.0.3"},
      {:phoenix_ecto, "~> 1.1"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.1"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:cowboy, "~> 1.0"},
+     {:ex_admin, github: "smpallen99/ex_admin"},
      {:comeonin, "~> 1.3"}]
   end

diff --git a/web/router.ex b/web/router.ex
index 42248a5..bed69de 100644
--- a/web/router.ex
+++ b/web/router.ex
@@ -1,5 +1,6 @@
 defmodule Myapp.Router do
   use Myapp.Web, :router
+  use ExAdmin.Router

   pipeline :browser do
     plug :accepts, ["html"]
@@ -13,6 +14,8 @@ defmodule Myapp.Router do
     plug :accepts, ["json"]
   end

+  admin_routes :admin
+
   scope "/", Myapp do
     pipe_through :browser # Use the default browser stack

diff --git a/web/subdomain_router.ex b/web/subdomain_router.ex
index e080ee0..9fb1022 100644
--- a/web/subdomain_router.ex
+++ b/web/subdomain_router.ex
@@ -1,5 +1,6 @@
 defmodule Myapp.SubdomainRouter do
   use Myapp.Web, :router
+  use ExAdmin.Router

   pipeline :browser do
     plug :accepts, ["html"]
@@ -9,6 +10,8 @@ defmodule Myapp.SubdomainRouter do
     plug :put_secure_browser_headers
   end

+  admin_routes :admin
+
   scope "/", Myapp.Subdomain do
     pipe_through :browser # Use the default browser stack

**Comment by tispratik** [comment]
Oh wow! Thank you very much for taking time to look into it @smpallen99.
So, the difference i see is that you also added it to the sub domain router. 
I will check it out.

**Comment by smpallen99** [comment]
The other difference is that I used the newer version of ex_admin that does not have a dependency on haml. I noticed that you project code had the haml config commented out. I’m wondering if that was not setup properly and was causing your issues. I converted the haml templates into eex on ex_admin, so this dependency is not needed anymore.

I did not try your subdomain access to admin, only `http://localhost:4000/admin`

Don’t forget to do a `mix do deps.update ex_admin, deps.compile ex_admin` to get the the latest version.

Steve

**Comment by tispratik** [comment]
Awesome! I got it working after `mix do deps.update ex_admin, deps.compile ex_admin`.
It worked even after removing the following lines from the subdomain router as expected.

```ruby
use ExAdmin.Router
admin_routes :admin
```

I am sooo glad to see the admin screen after many tries :+1: 
Thanks a bunch!
