### ISSUE TITLE
Actions statement not working as intended

### ISSUE THREAD

**Issue by matthijsgroen** [smpallen99/ex_admin#163]
## Reproduction

```
  register_resource Project.Model do
    actions :all, only: [:show, :edit]
  end
```

## Expected

* Ony able to view or edit the resource in index and show pages

## Actual

* Bulk deletion on index is still available
* Delete option at each record is still available
* Edit action on show page is not available

**Comment by smpallen99** [comment]
I did some work in this area last night. action_item was not working. I'll fix the actions this morning. Should see an update later today

**Comment by smpallen99** [comment]
Fix pushed. Remember to use `action_items only: [:show]` syntax now.

**Comment by smpallen99** [comment]
oops. missed the batch action
