### ISSUE TITLE
Collection_action not working?

### ISSUE THREAD

**Issue by matthijsgroen** [smpallen99/ex_admin#164]
The documented example of 'collection_action' does not add a action button anywhere on the page.

I also have not seen any use of it in the demo app. I don't get errors, but it is not working either.

Also, is there a way to add own bulk actions? As far as I could see there is no option for it, but is it planned?  (would help to bulk enable/disable users for our system)

**Comment by smpallen99** [comment]
Will have an fix for this today too

**Comment by matthijsgroen** [comment]
I could also not find how member_actions are supposed to work. For now I created links with:

admin_resource_path(u) <> "/enable" and implemented the routes myself.

Are there examples for that?

**Comment by smpallen99** [comment]
After reviewing the current implementation, I missed generating the action links. The current member action is working in that it provides the action. But you have to manually generate the route and the action_item to display the link. Like this:

```elixir
    member_action :unlock,  &__MODULE__.unlock_user/2
    action_item :show, fn id ->
      action_item_link "Lock User!", href: "/admin/users/lock/#{id}", "data-method": :put
    end

    # router
    put "/:resource/unlock/:id", AdminResourceController, :unlock
```

I'll work on an update to have the member_action macro create the link automatically.

**Comment by romul** [comment]
@smpallen99 
Should be:
`put "/:resource/:id/unlock", AdminResourceController, :unlock`
and then URL-helper would work:
`ExAdmin.Utils.admin_resource_path(resource, :unlock)`

**Comment by smpallen99** [comment]
Full support now for creating the buttons for member and collection_action.

**Comment by smpallen99** [comment]
@romul I'll look at your route suggestion

**Comment by romul** [comment]
@smpallen99 
Smth like `ExAdmin.Utils.admin_resource_path(resource, :member, [action])` should work.
But why not just use Phoenix features? Anyone could add custom actions without introducing `member and collection_action macros`... It's definitely overcomplicated.

**Comment by smpallen99** [comment]
@romul Not sure I'm following. Are you suggesting that a route be manually added to their router for each custom action? 

The benefit of the member and collection_action macros is that they add the action, the processing, and the action button all from the resource file. No need to touch any other file. Is this the complicated part?

I can't shorten the path by removing the member or collection part since the paths will conflict with the association paths. I tried dynamically building routes from the modules config but I can't get that to work. Some dependency compile error that I can't figure out.

**Comment by romul** [comment]
> Are you suggesting that a route be manually added to their router for each custom action?

Yes. Explicit is better than implicit.
Gems like resource_controller and inherited_resources were always the source of complicated bugs, b/c these abstractions leak in complicated cases.
I feel like you want to make their clone in Elixir, but I guess it could not be done in Elixir-way.
In Elixir you have only functions, so you don't really need to extend existing controllers to provide extra-actions. Yes, we have many before actions (like plugs, filters, etc.). But it could be 1) simplified; 2) extracted to separate module and transparently mixed in user controllers

All that user really need to add whenever that he wants is:
```elixir
  scope "/admin", ExAdmin do
    pipe_through :browser
    get "/any/route", MyApp.MyController, :custom
    admin_routes
  end
```

```elixir
defmodule MyApp.MyController do
  use ExAdmin.Web, :resource_controller

  def custom(conn, params) do
    # ...
  end
end
```

**Comment by romul** [comment]
In other words I don't like an idea to treat ex_admin as magic black box, I'd prefer to see it simple to understanding and highly extensible as regular part of an user's project.

**Comment by smpallen99** [comment]
@romul Created issue #166 to track discussions like this.
