### ISSUE TITLE
heroku installation error

### ISSUE THREAD

**Issue by sobolevn** [smpallen99/ex_admin#178]
When trying to run `mix admin.install` on heroku this error shows up:

```
remote:        * creating css files
remote:        * creating js files
remote:        ** (File.Error) could not read file /tmp/build_de9a0426198c91c9e5245f5e2a4843d9/deps/ex_admin/web/static/vendor/active_admin/application.js.js: no such file or directory
remote:            (elixir) lib/file.ex:244: File.read!/1
remote:            lib/mix/tasks/admin.install.ex:229: anonymous fn/3 in Mix.Tasks.Admin.Install.read_active_admin_js/3
remote:            (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
remote:            lib/mix/tasks/admin.install.ex:220: Mix.Tasks.Admin.Install.do_active_admin_js/1
remote:            lib/mix/tasks/admin.install.ex:63: Mix.Tasks.Admin.Install.do_assets/1
remote:            lib/mix/tasks/admin.install.ex:43: Mix.Tasks.Admin.Install.do_install/1
remote:            (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

It does not really mater how to run it:
1. Via `heroku run ...`
2. Via `buildback`'s `compile` (as shown in error)
3. Via `heroku run bash` and manually trying to get it to work

What did I miss?

**Comment by smpallen99** [comment]
I'm sorry, but I don't have very much experience with heroku. But it looks like your trying to run mix admin.install on heroku?

**Comment by sobolevn** [comment]
Yes, I am running this command when deploying.  Here's my workflow:

1. `priv/static` is ignored
2. When deploying I run `brunch build --production && phoenix digest` via [heroku-buildpack-phoenix-static](https://github.com/elixir-lang-moscow/heroku-buildpack-phoenix-static)
3. Next step I was trying to run `mix admin.install --no-config --no-route --no-dashboard` Since I don't want to concat admin files into my static assets. 

I tried to run it as a buildpack step. Before and after `brunch build`. I also have tried to do it with `.travis.yml`: [example](https://github.com/elixir-lang-moscow/site/blob/master/.travis.yml). No luck either.

Maybe there's another workflow?

**Comment by erikmueller** [comment]
What about running `mix admin.install` locally, copying ex_admin's asset into your `web/assets` under `vendor` or `ex_admin` (and version them - that's what I do) and the let the build step simply copy them to `priv/static` (I'm also doing this with the buildpack-phoenix-static)

**Comment by smpallen99** [comment]
I committed a change into master last week. admin.install now installs the assets into `web/static` and updates your `brunch-config.js` file with instructions. on how to update it. This should resolve your issue.

**Comment by smpallen99** [comment]
@sobolevn I believe this should be resolved with the support for brunch assets. I have not heard back from you so I'm assuming this resolved your issue. Closing the issue. Please reopen if the brunch assets does not resolve your issue.

**Comment by sobolevn** [comment]
Sorry for the long response: just didn't have the time to work on this project lately.

@erikmueller this will work, no doubts. I think I will use it as a workaround.

@smpallen99 That's a good job! But actually I don't like the idea of modifying `brunch.js` since it may break things unintentionally. Furthermore, projects can use `gulp`, `webpack` or any other tool.

Maybe it would be a better idea to maintain these static files as a `npm` package? Project is totally growing into a separate github-organization ;)

**Comment by sobolevn** [comment]
That's how `phoenix` itself manages to solve the same problem:

`package.json`:

```json
{
  "name": "your_app_name",
  "devDependencies": {
    "phoenix": "file:deps/phoenix",
    "phoenix_html": "file:deps/phoenix_html"
  }
}
```
