### ISSUE TITLE
Custom Ecto field issues

### ISSUE THREAD

**Issue by sobolevn** [smpallen99/ex_admin#183]
I have created a simple slug field for Ecto: https://github.com/sobolevn/ecto_autoslug_field
Here's it's [`Type` definition](https://github.com/sobolevn/ecto_autoslug_field/blob/master/lib/ecto_autoslug_field/type.ex).

After adding it to the project it looks something like this:

``` elixir
defmodule ElixirLangMoscow.SpeakerSlug do
  use EctoAutoslugField.Slug, from: [:name, :company], to: :slug
end

defmodule ElixirLangMoscow.Speaker do
  use ElixirLangMoscow.Web, :model
  use Arc.Ecto.Model

  alias ElixirLangMoscow.SpeakerSlug

  schema "speakers" do
    field :name, :string
    field :company, :string

    field :slug, SpeakerSlug.Type
    field :avatar, ElixirLangMoscow.Avatar.Type

    timestamps
  end
```

But `ex_admin` now treats this field as a `<input type="file" />`:
<img width="687" alt="2016-07-23 23 36 55" src="https://cloud.githubusercontent.com/assets/4660275/17080181/640b4b42-512e-11e6-8ef5-c692f2dcaae7.png">

I can easily change it's `type` like this:

``` elixir
   form admin do
      inputs do
        input admin, :name
        input admin, :company
        input admin, :slug, type: :text
        input admin, :avatar, type: :file
      end
    end
```

But does suppose to be like so? Is it possible to customize it's type somewhere just once?

**Comment by smpallen99** [comment]
Try adding a defimpl for it somewhere in your project. See https://github.com/smpallen99/ex_admin/blob/5c1bf64f19767f709b8608e3e2fe81e8e420945d/lib/ex_admin/render.ex for currently defined implementations. I'm not 100% sure this will do everything. Let me know how it goes and we can discuss further from there.

**Comment by sobolevn** [comment]
Nope, that did not work. It is not even called.

```elixir
defmodule ElixirLangMoscow.EventSpeakerSlug do
  use EctoAutoslugField.Slug, from: :title, to: :slug
end

defimpl ExAdmin.Render, for: ElixirLangMoscow.EventSpeakerSlug.Type do
  def to_string(data), do: raise "called"
end

defmodule ElixirLangMoscow.EventSpeaker do
  schema "event_speakers" do
    ...
    field :slug, EventSpeakerSlug.Type
    ...
  end
end
```

**Comment by smpallen99** [comment]
@sobolevn try 

```
defimpl ExAdmin.Render, for: ElixirLangMoscow.EventSpeakerSlug do
  def to_string(data), do: raise "called"
end
```

**Comment by sobolevn** [comment]
Did not help, not called.

**Comment by romul** [comment]
@sobolevn  Now you could specify matching rules in the config:
``` elxiir
config :ex_admin,
  # ...
  field_type_matching: %{
    ElixirLangMoscow.SpeakerSlug.Type => :string,
    ElixirLangMoscow.Avatar.Type => :file
  }
```

**Comment by vraravam** [comment]
@smpallen99 , @romul - I have a similar issue. I am trying to register a renderer for `Timex.Ecto.Date` using the following code:
```
defimpl ExAdmin.Render, for: Timex.Ecto.Date do
  def to_string(dt) do
    ....
  end
end
```
Since this is not even called, I'm not able to handle this in a consistent manner. Could you please suggest a fix? I'm using the HEAD of the master branch of ex_admin from your repo.

**Comment by vraravam** [comment]
@romul - nope, that doesn't work either. (I assume that the `field_type_matching` is instead of the `defimpl ExAdmin.Render, for: Timex.Ecto.Date`...?

**Comment by vraravam** [comment]
@romul , @smpallen99 - I also tried the `raise "called"` as suggested in one of the previous comments, and can attest that its definitely not being invoked. But, since I am using Elixir 1.3.4, I switched over to using the built-in `calendar` structs, instead of coercing `Timex` into my codebase.

**Comment by smpallen99** [comment]
I don't believe there is anything wrong with ExAdmin.Render protocol for Timex. I just tested the following successfully on ExAdmin master.

With the following resource file:

```elixir
defmodule ManyThrough.ExAdmin.User do
  use ExAdmin.Register

  register_resource ManyThrough.User do
    index do
      column :name
      column :updated_at
      column :inserted_at
    end
  end
end
```

After adding Timex dependencies:

```elixir
     {:timex, "~> 3.0"},
     {:timex_ecto, "~> 3.0"},
```

And adding 

```elixir
# web/web.ex
def model do
  quote do
    use Ecto.Schema
    use Timex.Ecto.Timestamps
    # ...
  end
end
```

I get the following error for the User index page

```bash
Request: GET /admin/users
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol ExAdmin.Render not implemented for #<DateTime(2016-12-10T18:51:04Z Etc/UTC)>
...
```

Then I created the following file:

```elixir
# web/render.ex
defimpl ExAdmin.Render, for: DateTime do
  def to_string(dt) do
    DateTime.to_string dt
  end
end
```
And the index page displays the timestamps correctly. 

As you can see from the error, its the `DateTime` struct that does not have the protocol implemented, so implementing that protocol fixed the issue.

**Comment by smpallen99** [comment]
@vraravam  for the ~D[...] error, try implementing the protocol for `Date`. Here is how i figured out the struct.

```
iex(7)> %{__struct__: st} = ~D[2016-12-07]
~D[2016-12-07]
iex(8)> st
Date
iex(9)>
```

Since Ecto now uses the Elixir built in types, I'll add these to the ExAdmin Render implementations.

**Comment by vraravam** [comment]
@smpallen99 - Thanks for the detailed steps. I was missing a couple of steps:
1. The file I was trying to put the `defimpl` was in the `lib` folder - which wasn't getting loaded.
2. I was also missing the `use` statement.

Do you think this bit of detail might be helpful for others? If so, would be mind putting it in the docs?

**Comment by smpallen99** [comment]
@vraravam just pushed an update to support rendering Elixir's Date, Time, and DateTime types. So you don't need to implement the Render protocol for these now.

**Comment by smpallen99** [comment]
@vraravam It should not matter where you put the file containing defimpl. Just make sure its not in a module and that the file type is .ex. It appears that you were trying to implement a protocol for Timex.Ecto.Date, where the error was telling you the protocol for ~D[…] was not implemented. 

I will be documenting the `field_type_matching` config option.

**Comment by grahac** [comment]
Hi,  Just an FYI that I recently uploaded ExAdmin and am having the same problems with it not recognizing ~D[...].  I am using CalEcto and have tried the following in my config but to no avail.  
   field_type_matching: %{
    Calecto.Date => Ecto.Date
   }

Thoughts on what I am doing wrong?  

Thanks!!
