### ISSUE TITLE
custom password field issues 

### ISSUE THREAD

**Issue by yeelone** [smpallen99/ex_admin#189]
I have created a field for user auth : password_hash , 
`
  schema "users" do
    field :name, :string
    field :username, :string
    field :password, :string, virtual: true
    field :password_hash, :string

 defp put_pass_hash(changeset) do
      case changeset do
        %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
          put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
        _ ->
          changeset
        end
    end
`
i wanna know how to call the put_pass_hash()  function when adding or updating a user model in ex_admin?

**Comment by smpallen99** [comment]
You do all that from your changeset. Nothing to do in ExAdmin. You can look at [ContactDemo](https://github.com/smpallen99/contact_demo) and checkout a commit before I integrated Coherence, you should see how to do it.
