### ISSUE TITLE
Add support and docs for installing css and js files when using brunch. 

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#19]
Currently, ExAdmin copies the css and js files into your project's priv/static/ directory. This is an issue if you are using brunch, and don't have the priv/static tracked in git. 

To manually fix this, run `mix admin.install`. Then move the `active_admin.css.css`, `jquery-ujs.js.js` and `jquery.js` files to your project's `web/static/vendor` directory. Then edit your `brunch-config.js` like this.

``` javascript
    javascripts: {
      joinTo: {
       "js/app.js": [/^(web\/static\/js)/,
       "deps/phoenix/web/static/js/phoenix.js",
       "deps/phoenix_html/web/static/js/phoenix_html.js"],
       "js/jquery-ujs.js.js": ["web/static/vendor/jquery-ujs.js.js"],
       "js/jquery.js": ["web/static/vendor/jquery.js"],
     }
  },
    stylesheets: {
      joinTo: {
        "css/app.css": [/^(web\/static\/css)/],
        "css/active_admin.css.css": ["web/static/vendor/active_admin.css.css"],
      }
    },
```

**Comment by tispratik** [comment]
Thanks, this is helpful.

**Comment by sublimecoder** [comment]
I attempted to use your config, but I kept getting brunch compiled but did not write the files to the desired destination. I ended up using the solution mentioned here. 
https://github.com/smpallen99/ex_admin/issues/81
