### ISSUE TITLE
Support resources with the same module name but within different namespace

### ISSUE THREAD

**Issue by wojtekmach** [smpallen99/ex_admin#191]
In my app I have Bank.Account & Auth.Account schemas. I'm registering them in ExAdmin but both end up with the the same url: `/accounts/:id` and so in effect just the one defined later can be managed. I tried setting `:controller_route` but it didn't help.

I created a workaround in my fork (https://github.com/wojtekmach/ex_admin/commit/5912810cfd048df6cf483ffeccf4c05355a2cb5e) and this works like this:

``` elixir
register_resource Auth.Account do
  menu label: "Auth Accounts"
  options resource_name: "auth_account", controller_route: "auth_accounts"

  # ...
end

register_resource Bank.Ledger.Account do
  menu label: "Bank Accounts"
  options resource_name: "bank_account", controller_route: "bank_accounts"

  # ...
end
```

but I'm not sure it's the best solution (and implementation of that solution). Could something like this be supported in ExAdmin?

**Comment by hrefhref** [comment]
Any updates on this ?

**Comment by quolpr** [comment]
+1
