### ISSUE TITLE
When Adding scope to resource it no longer populates any data

### ISSUE THREAD

**Issue by andrewcottage** [smpallen99/ex_admin#192]
When adding 

```
defmodule Houser.ExAdmin.Facility do
  use ExAdmin.Register
  require ExAdmin.Register

  register_resource Houser.Facility do
    scope :with_auction, fn(q) ->
      where(q, [f], not(is_nil(f.auction_date_and_time_1)))
    end
    
    scope :verified, fn(q) ->
      where(q, [f], f.verified == "Yes")
    end

    sidebar "Bulk Update", only: :index do
      Phoenix.View.render(Houser.FacilityView, "bulk_update.html", %{conn: conn})
      |> Phoenix.HTML.safe_to_string
      |> raw
    end

  end
end
```

![screenshot from 2016-08-11 10 20 56](https://cloud.githubusercontent.com/assets/4549986/17591714/50a3e298-5fad-11e6-946f-d8136b7f82ac.png)

and when I remove it 
```
defmodule Houser.ExAdmin.Facility do
  use ExAdmin.Register
  require ExAdmin.Register

  register_resource Houser.Facility do
    # scope :with_auction, fn(q) ->
    #   where(q, [f], not(is_nil(f.auction_date_and_time_1)))
    # end
    #
    # scope :verified, fn(q) ->
    #   where(q, [f], f.verified == "Yes")
    # end

    sidebar "Bulk Update", only: :index do
      Phoenix.View.render(Houser.FacilityView, "bulk_update.html", %{conn: conn})
      |> Phoenix.HTML.safe_to_string
      |> raw
    end

  end
end
```
It populates again

![screenshot from 2016-08-11 10 32 22](https://cloud.githubusercontent.com/assets/4549986/17592382/19ee9240-5fb0-11e6-8de0-bf3f2d650ea9.png)

I'm on the Master branch

**Comment by smpallen99** [comment]
I just tested a project with current master and its working fine. I suspect you have an issue with the queries. I suggest you try some of the following:

* add a default all scope `scope :all, default: true` and see if that returns all the records.
* Try `where(q, [f], f.verified == true)` for your verified scope
* Try logging the the query returned by the scope block and then run the query manually to see if it returns records. Something like:
```
scope :with_auction, fn(q) ->
  query = where(q, [f], not(is_nil(f.auction_date_and_time_1)))
  IO.puts "with_auction query: #{inspect query}"
  query
end
```

**Comment by andrewcottage** [comment]
Not sure why but when I added `scope :all, default: true` it started working.
