### ISSUE TITLE
"Internal server error" ARC Image Upload

### ISSUE THREAD

**Issue by renews** [smpallen99/ex_admin#213]
I dont know what changes you made, but now we cant get uploads to work  anymore, even on your own demos it returns a internal server erro... Example of the error as follow

`** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Arc.File.new/1
        lib/arc/file.ex:5: Arc.File.new(%{"__struct__" => Plug.Upload, "content_type" => "image/jpeg", "filename" => "2016-04-18 16.50.25 HDR-2.jpg", "path" => "/tmp/plug-1474/multipart-380143-369974-1"})
        lib/arc/actions/store.ex:9: Arc.Actions.Store.store/2
        lib/arc_ecto/type.ex:5: Arc.Ecto.Type.cast/2
        (ecto) lib/ecto/type.ex:564: Ecto.Type.cast/2
        (ecto) lib/ecto/changeset.ex:464: Ecto.Changeset.cast_field/8
        (ecto) lib/ecto/changeset.ex:423: Ecto.Changeset.process_param/8
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3`

**Comment by renews** [comment]
Did not mean to sound harsh or anything, im sorry if i did.

**Comment by nicholasjhenry** [comment]
@smpallen99 I've tracked the issue down to this commit:

https://github.com/smpallen99/ex_admin/commit/5c1bf64f19767f709b8608e3e2fe81e8e420945d

Arc is pattern matching on a Plug struct (i.e. atoms with keys) but `param_stringify_keys/1` is converting the Plug struct to a map where the keys are now strings.

**Comment by nicholasjhenry** [comment]
Sorry @smpallen99 I missed this PR #184 for the fix.

**Comment by romul** [comment]
Fix merged: https://github.com/smpallen99/ex_admin/commit/ae45f042082f5d1f9b80474ef27beff2a43b568e
