### ISSUE TITLE
Question: Can someone tell me what I'm not doing correctly?

### ISSUE THREAD

**Issue by rakr** [smpallen99/ex_admin#218]
[My ExAdminSample](https://github.com/rakr/ExAdminSample)

This is a bare Phoenix app,I think I have followed the instructions to have ExAdmin working properly, but the page that I see is without style.

Thanks in advance

<img width="1071" alt="exadminsample" src="https://cloud.githubusercontent.com/assets/110558/19034391/dfbf3fba-89ae-11e6-9b0a-27c6c7e3a028.png">

**Comment by smpallen99** [comment]
Follow the instructions added to your brunch-config.js file

**Comment by rakr** [comment]
Thanks @smpallen99, but I have followed the instructions and replaced the blocks for JavaScript and CSS.
