### ISSUE TITLE
Upgrade to latest Phoenix?

### ISSUE THREAD

**Issue by tispratik** [smpallen99/ex_admin#23]
$ mix deps.get
Running dependency resolution
Looking up alternatives for conflicting requirements on phoenix
  Activated version: 1.1.2
  From mix.exs: ~> 1.1.2
  From deps/ex_admin/mix.exs: ~> 1.0.2

** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

**Comment by smpallen99** [comment]
I'm working on a branch to support elixir 1.2 and phoenix 1.1.2.

**Comment by tispratik** [comment]
Thanks @smpallen99
