### ISSUE TITLE
CSV export should follow the same columns definition as index table

### ISSUE THREAD

**Issue by vraravam** [smpallen99/ex_admin#232]
I was able to change the ex_admin resource page (eg taken is from [contact_demo](https://github.com/smpallen99/contact_demo/blob/master/web/admin/contact.ex) codebase) to:
```elixir
    defmacro contents do
      quote do
        selectable_column

        column :first_name
        column :last_name
        column :email
        column :category
        column :phone_numbers, fn(contact) ->
          text PhoneNumber.format_phone_numbers_abbriviated(contact.phone_numbers)
        end

        actions
      end
    end

    index do: contents
```

The intent of this is that for any exposed resource, I would like the CSV export to "follow" the same columns, etc as the index table.
For eg, in an equivalent rails codebase using the active_admin gem, I might have done:
```ruby
  column_definition = proc do
    selectable_column unless params.key?(:format)
    column(:first_name)
    column(:last_name)
    column(:email)
    column(:category)
    actions unless params.key?(:format)
  end

  index(&column_definition)
  csv(&column_definition)
```

How can I achieve the same in ex_admin? Any help would be really appreciated.

**Comment by smpallen99** [comment]
This would be a huge architectural change to ex_admin. With new csv list API, I don't see how the value of the feature would exceed the cost to implement. I suggest you use `csv [:first_name, :last_name, :email, {:category, &(&1.category}]`.
