### ISSUE TITLE
CSV block generates exception when placed before the show block

### ISSUE THREAD

**Issue by vraravam** [smpallen99/ex_admin#233]
I copied the following [code](https://github.com/smpallen99/ex_admin/blob/master/lib/ex_admin/csv.ex#L31):
```elixir
          csv do
            column "Surname", fn c -> c.last_name end
            column "Given", fn c -> c.first_name end
            column "Category", fn c -> c.category.name end

            column "Groups", fn c ->
              Enum.map(c.groups, &(&1.name))
              |> Enum.join("; ")
            end

            for label <- PhoneNumber.all_labels do
              column label, fn c ->
                c.phone_numbers
                |> PhoneNumber.find_by_label(label)
                |> Map.get(:number, "")
              end
            end
```

But, none of the example blocks for custom CSV seems to work. Is the documentation out of date? I also referred to the tests for the csv module, but they are only testing the inner method - not the macro itself.
Please help resolve this issue - I'm stuck with my project.

**Comment by vraravam** [comment]
This is the error stack that I get:
```elixir
== Compilation error on file web/admin/contact.ex ==
** (CompileError) lib/ex_admin/show.ex:89: expected var "columns" (context ExAdmin.CSV) to expand to an existing variable or be part of a match
    (elixir) expanding macro: Kernel.var!/2
    lib/ex_admin/show.ex:89: HimachalErp.ExAdmin.Contact.show_view/2
    expanding macro: ExAdmin.CSV.column/1
    lib/ex_admin/show.ex:89: HimachalErp.ExAdmin.Contact.show_view/2
    expanding macro: ExAdmin.Show.table_for/3
    lib/ex_admin/show.ex:88: HimachalErp.ExAdmin.Contact.show_view/2
    expanding macro: ExAdmin.Show.table_for/2
    lib/ex_admin/show.ex:88: HimachalErp.ExAdmin.Contact.show_view/2
    expanding macro: ExAdmin.Show.panel/2
    lib/ex_admin/show.ex:87: HimachalErp.ExAdmin.Contact.show_view/2
    expanding macro: Xain.markup/2
    lib/ex_admin/show.ex:54: HimachalErp.ExAdmin.Contact.show_view/2
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by smpallen99** [comment]
what version of ex_admin are you using?

**Comment by smpallen99** [comment]
The documentation is out of date. The column format still works, but calling column inside does not work. No error, but does not generate the columns. I've updated the contacts admin resource to use the list api.

**Comment by vraravam** [comment]
@smpallen99 - I incorporated your changes in `contact.ex` - but am still getting the error. Could you please reverify? I have verified that the `mix.lock` is the same as the one that you merged into `contact_demo`. If not, I can attach it to this ticket.

**Comment by smpallen99** [comment]
Let me see your complete contact.ex file please.

**Comment by vraravam** [comment]
@smpallen99 - Here is the code: https://github.com/vraravam/contact_demo/blob/master/web/admin/contact.ex

**Comment by smpallen99** [comment]
It appears that the issue is with defining the csv block ahead of the show block. Moving the csv block below the show block fixes the issue. I'll reopen the issue and change the title appropriately.
