### ISSUE TITLE
Returning new params in before_filter doesnt retain the new params

### ISSUE THREAD

**Issue by vraravam** [smpallen99/ex_admin#242]
According to [this](https://github.com/smpallen99/ex_admin/blob/master/lib/ex_admin/register.ex#L376), we can return a tuple with the new parameters, but that doesn't get propogated to the actual method calls after the `before_filter`. I suspect that the ball is dropped in [resource_controller.ex](https://github.com/smpallen99/ex_admin/blob/master/web/ex_admin/resource_controller.ex#L131).

**Comment by smpallen99** [comment]
Please provide an example of this issue.

**Comment by vraravam** [comment]
Was not able to reproduce it in master HEAD as of this moment - but, still seems to be a bug in `v0.4.2`
