### ISSUE TITLE
Potentially missing PR code that was merged

### ISSUE THREAD

**Issue by julianrogmans** [smpallen99/ex_admin#250]
#65 This PR appears to add support for Timex.Ecto.Date in the admin panel. But when browsing master I can't seem to find it. Was this refactored to something else or accidentally dropped?

This is what is happening currently.
Thanks

![image](https://cloud.githubusercontent.com/assets/10566942/20910278/75b1198e-bb15-11e6-9359-68d96a34527f.png)

**Comment by smpallen99** [comment]
I pulled back in the code from #65. However, that may not fix your issue. If not, you should implement the ExAdmin.Render protocol for the desire types in your project. I'm not going to implement them for Timex since i don't want to add the Timex dependency into the ex_admin.

**Comment by OvermindDL1** [comment]
> I'm not going to implement them for Timex since i don't want to add the Timex dependency into the ex_admin.

You can wrap the defmodule/defprotocol/defimpl in a `Code.ensure_loaded?(Atom)` test, such as:
```elixir
if Code.ensure_loaded?(Timex) do
  defimpl Blah do
    Blah blah
  end
end
```
All without adding a dependency.

**Comment by OvermindDL1** [comment]
However, do note, the latest version of Timex does use Elixir's native calendar format instead of its own custom format, so the user should probably update Timex anyway.

**Comment by smpallen99** [comment]
@OvermindDL1 I created the render protocol to allow for adding custom types. So I don't see the need to add this ex_admin.

**Comment by vraravam** [comment]
@smpallen99 , @romul - Is there a location where we need to put the `defimpl ExAdmin.Render, for: Timex.Ecto.Date`? I tried putting it into the `lib` folder - no luck :(
