### ISSUE TITLE
Does not allow custom css or js files

### ISSUE THREAD

**Issue by vraravam** [smpallen99/ex_admin#251]
Looking through the code in https://github.com/smpallen99/ex_admin/blob/master/web/templates/layout/admin_lte2.html.eex - looks like we cannot customize the css and js. Please include the following line (for css):
```
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
```
Also, please include a corresponding line for `app.js`

cc @smpallen99

**Comment by smpallen99** [comment]
There is already a way to add a custom head_template by setting `config :ex_admin, :head_template` with `{layout, template}`. So you can add your own css and js in there.

**Comment by vraravam** [comment]
@smpallen99 - Thanks, I had not gone through that part of the code, and have followed your suggestion and implemented the same.
