### ISSUE TITLE
Missing underscore in resource name when generating form for either create or edit

### ISSUE THREAD

**Issue by vraravam** [smpallen99/ex_admin#257]
Due to this, when the user submits the form, the resource key within the params object is missing the underscore, and thus there is no changeset.

This is with the latest version of `ex_admin`.

**Comment by smpallen99** [comment]
Cannot reproduce

**Comment by vraravam** [comment]
@smpallen99 : Please run the latest code from this branch/commit: https://github.com/vraravam/contact_demo/commit/44a4e36407d7d5224df158e2dab6643133356716 - and take a look at the 'Purchase Order' : index page, show page and form for edit/update - collectively they showcase the bug.

**Comment by vraravam** [comment]
@smpallen99 @romul - could you please post the status of this issue? It's a blocker for me (and others I think) who have models/entities that have underscores in the name.
If you can give me a hint, I can try and start working on a PR for fixing it.

**Comment by smpallen99** [comment]
@vraravam Just to be clear, this is a cosmetic issue where the space and capitalization is missing, but the update is working. Correct?

**Comment by vraravam** [comment]
@smpallen99 - no, if you see the screenshot of the console log that I attached above, the key is `purchaseorder` - which doesn't seem to update anything in the backend.

**Comment by smpallen99** [comment]
I have your update checked out and the update is working. I agree that "purchaseorder" is not the correct key, but it appears to be working anyway.

```
[info] module=Plug.Logger line=27 function=call/2 POST /admin/purchase_orders/14
[debug] module=Phoenix.Logger line=25 function=phoenix_controller_call/3 Processing by ExAdmin.AdminResourceController.update/2
  Parameters: %{"_csrf_token" => "DCUJQAoFfzZcIk0MKBslaBEBGXcKJgAAdWsqMoMtwRuNGXD2exi/Og==", "_method" => "put", "commit" => "Update Purchaseorder", "id" => "14", "purchaseorder" => %{"buying_price" => "21.23", "currency_code" => "INR", "name" => "Jameson Upton 3"}, "resource" => "purchase_orders", "utf8" => "✓"}
  Pipelines: [:protected]
[debug] module=Ecto.LogEntry line=41 function=log/1 QUERY OK source="purchase_orders" db=2.8ms queue=0.1ms
SELECT p0."id", p0."placed_on", p0."name", p0."buying_price", p0."currency_code", p0."inserted_at", p0."updated_at" FROM "purchase_orders" AS p0 WHERE (p0."id" = $1) [14]
[debug] module=Ecto.LogEntry line=41 function=log/1 QUERY OK db=0.1ms queue=0.1ms
begin []
[debug] module=Ecto.LogEntry line=41 function=log/1 QUERY OK db=7.3ms
INSERT INTO "versions" ("action","item_id","item_type","object","whodoneit_id","whodoneit_name","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id" ["update", 14, "PurchaseOrder", %{buying_price: #Decimal<21.23>, currency_code: "INR", id: 14, inserted_at: #Ecto.DateTime<2016-12-16 03:10:06>, name: "Jameson Upton 2", placed_on: #Ecto.Date<2016-12-14>, updated_at: #Ecto.DateTime<2016-12-16 03:17:23>}, 1, "Demo Admin", {{2016, 12, 16}, {3, 34, 32, 0}}, {{2016, 12, 16}, {3, 34, 32, 0}}]
[debug] module=Ecto.LogEntry line=41 function=log/1 QUERY OK db=0.6ms
UPDATE "purchase_orders" SET "name" = $1, "updated_at" = $2 WHERE "id" = $3 ["Jameson Upton 3", {{2016, 12, 16}, {3, 34, 32, 0}}, 14]
[debug] module=Ecto.LogEntry line=41 function=log/1 QUERY OK db=0.3ms
commit []
```

**Comment by smpallen99** [comment]
@vraravam Give it a try now.

**Comment by vraravam** [comment]
@smpallen99: Thanks - this works now!
