### ISSUE TITLE
Unable to set page-specific javascript block in forms

### ISSUE THREAD

**Issue by vraravam** [smpallen99/ex_admin#259]
Please see the commit in this branch: https://github.com/vraravam/contact_demo/tree/page-specific-javascript-not-rendering

In the 'Groups' resource, for the form object, and using the `script` block, I am unable to get the script to be rendered.
<img width="1038" alt="screen shot 2016-12-14 at 10 56 28 pm" src="https://cloud.githubusercontent.com/assets/69629/21193234/8bc8aba4-c251-11e6-8b0a-e07009352d94.png">

**Comment by smpallen99** [comment]
try this
```elixir
  form something do
    inputs do
      # ...
    end
    javascript do
      """
      alert('test');
      """
    end
  end
```

**Comment by vraravam** [comment]
@smpallen99 - thanks, that works!
