### ISSUE TITLE
Date and boolean fields are always nil.

### ISSUE THREAD

**Issue by r-icarus** [smpallen99/ex_admin#26]
Is there a default format for dates?  Is there any way to show a boolean as a check box? 
Right now both are shown as text inputs but when I submit the form the value is always nil (for booleans)

**Comment by smpallen99** [comment]
Just pushed support for datetime, date, time, and boolean fields to master.

**Comment by r-icarus** [comment]
I just tried, this. It is amazing. Thank you!
