### ISSUE TITLE
Error compiling with Ecto 2.1.1

### ISSUE THREAD

**Issue by chrisortman** [smpallen99/ex_admin#267]
I get an error in a new phoenix project when I try to do `mix deps.compile` that is using Ecto 2.1.1

```
== Compilation error on file web/controllers/admin_association_controller.ex ==
** (CompileError) web/controllers/admin_association_controller.ex:3: module Ecto.Model is not loaded and could not be found
    expanding macro: ExAdmin.Web.__using__/1
    web/controllers/admin_association_controller.ex:3: ExAdmin.AdminAssociationController (module)
    (elixir) expanding macro: Kernel.use/2
    web/controllers/admin_association_controller.ex:3: ExAdmin.AdminAssociationController (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

```

**Comment by dy2k** [comment]
Ecto 2.1.1 has deprecated the use of Ecto.Model, need to import Ecto instead as in my fork: https://github.com/dy2k/ex_admin/commit/374cd3c7285a17b05d949944f11f29533d9caff0#diff-75c165bdf904a7a8b835dd36f41e6a93

Was thinking of creating a pull request

**Comment by chrisortman** [comment]
@dy2k I was too, I have it ready to go, why change to `Ecto` instead of `Ecto.Schema` ?
