### ISSUE TITLE
Installer generates inappropriate `xain` configuration

### ISSUE THREAD

**Issue by knewter** [smpallen99/ex_admin#27]
https://github.com/smpallen99/ex_admin/blob/master/lib/mix/tasks/admin.install.ex#L102

That should be a 2-tuple for {M, F} - i.e. `{Phoenix.HTML, :raw}`.  This caused me about 20 minutes of fiddling when I tried this out just now for the first time.

The project's awesome by the way :)

**Comment by smpallen99** [comment]
Thanks Josh. I updated the project to be compatible with exrm releases which don't support the Elixir &Module.function/arity syntax and forgot to update the mix task. Working on a fix now. Just thinking about  something to catch the issue when upgrading to this new format.

**Comment by smpallen99** [comment]
Fixed the mix.install task. Added compile time check and exception if not configured correctly.
