### ISSUE TITLE
Custom column label and render function prevent sorting?

### ISSUE THREAD

**Issue by naps62** [smpallen99/ex_admin#279]
I have a datetime column:

```
index do
  column :fetched_at
end
```

which is sortable by default (expected). But whenever I add a custom label, or a custom render function for each field (both of which I need), I can no longer sort the column:

```
index do
  column :fetched_at, label: "Last update", &(&1.fetched_at |> Timex.format("{relative}", :relative) |> elem(1))
```

Am I missing something here?

**Comment by christopheradams** [comment]
It would be great if there were a way to indicate the underlying column to sort a custom column on.
