### ISSUE TITLE
Temporary file path in register.ex is invalid on Windows

### ISSUE THREAD

**Issue by fhunleth** [smpallen99/ex_admin#28]
Admittedly, running on Windows is not a common practice for me, but I ran in to this hardcoded path while trying something out:

https://github.com/smpallen99/ex_admin/blob/bb20665a1bb2af2967e19f4b1bef666c963632e1/lib/ex_admin/register.ex#L43

As you'd expect, `/tmp` isn't on Windows.

**Comment by smpallen99** [comment]
I don't have a windows elixir setup to test a fix. Your welcome to submit a pull request with a fix, or I can take a stab at a fix on a branch and let you test it :)

**Comment by fhunleth** [comment]
I ended up giving up on Elixir on Windows - not due to ex_admin. I'm going to try to circle back at some point, since it would be nice to develop natively. If you happen to make a change that fixes this in the mean time, I'll gladly retest.

**Comment by smpallen99** [comment]
merged pull request
