### ISSUE TITLE
NaiveDateTime support

### ISSUE THREAD

**Issue by tralamazza** [smpallen99/ex_admin#281]
Ecto 2.1 `timestamps` uses `:naive_datetime` by default (which are just `NaiveDateTime`), I solved my rendering issues with something like:

```elixir
defimpl ExAdmin.Render, for: NaiveDateTime do
  def to_string(dt) do
    dt
    |> NaiveDateTime.to_erl
    |> ExAdmin.Utils.format_datetime
  end
end
```

**Comment by whitepaperclip** [comment]
Thanks, @tralamazza! I added this functionality into pull request #293.

**Comment by fire** [comment]
Also fails on:

```
[debug] ExAdmin.Filter: unknown type: :naive_datetime for field: :inserted_at
[debug] ExAdmin.Filter: unknown type: :naive_datetime for field: :updated_at
```

**Comment by whitepaperclip** [comment]
@fire Thanks for reporting this, I'll push a fix shortly.

**Comment by whitepaperclip** [comment]
@fire Pull requested submitted, waiting for @smpallen99 to merge. Thanks!

**Comment by fire** [comment]
Seems to be still happening. Any way I get get more debug info?

**Comment by whitepaperclip** [comment]
Ah! This is because Ecto's default `timestamps()` type is the symbol, `:naive_datetime`, and not the module `NaiveDateTime`. Hang on, pushing a second update.

**Comment by whitepaperclip** [comment]
Pull and try again.

**Comment by fire** [comment]
Looks better.

**Comment by whitepaperclip** [comment]
Alrighty then. @tralamazza can you close this?
