### ISSUE TITLE
Confusion in docs on one-to-many vs. many-to-many?

### ISSUE THREAD

**Issue by tslocke** [smpallen99/ex_admin#288]
Hi,

I'm looking at the docs on https://hexdocs.pm/ex_admin/ExAdmin.Form.html

Under the title "Rendering a has_many (one-to-many) relationship", this example is given 

```
inputs "Groups" do
  inputs :groups, as: :check_boxes, collection: MyProject.Group.all
end
```

which looks more like a many-to-many - the groups already exist and the form presents checkboxes to allow selection of which groups to join

Then, just below

> ExAdmin supports in-line creation of a has_many, through: (many-to-many) relationship. The example below allows the user to add/delete phone numbers on the contact form using the has_many command.

Phone numbers on a contact seems like a one-to-many, and the form controls created by the `has_many` macro seem appropriate for a one-to-many.

Am I misunderstanding something?

Thanks

**Comment by IdahoEv** [comment]
I wondered exactly the same thing. Is there an example use of this syntax in one of the demos we check against?  If it's actually many-to-many one of us should just issue a PR to the documentation.

**Comment by smpallen99** [comment]
Your right, the text is wrong. the code will handle a `has_many throught: ....` association which is many to many. I'll fix the docs.
