### ISSUE TITLE
Index rendering association xain error

### ISSUE THREAD

**Issue by britton-jb** [smpallen99/ex_admin#29]
I'm attempting to render an index view in ex_admin an it returns the following error:
`FunctionClauseError no function clause matching in Xain.Helpers.id_and_class_shortcuts/2`

Including this full stack trace:

```
    ** (FunctionClauseError) no function clause matching in Xain.Helpers.id_and_class_shortcuts/2
        lib/xain/helpers.ex:41: Xain.Helpers.id_and_class_shortcuts(nil, [value: "1"])
        lib/ex_admin/filter.ex:99: anonymous fn/3 in ExAdmin.Filter.build_field/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/filter.ex:97: ExAdmin.Filter.build_field/3
        lib/ex_admin/filter.ex:131: anonymous fn/4 in ExAdmin.Filter.check_and_build_association/3
        (elixir) lib/enum.ex:2462: Enum.do_find/3
        lib/ex_admin/filter.ex:67: ExAdmin.Filter.build_field/3
        lib/ex_admin/filter.ex:18: anonymous fn/4 in ExAdmin.Filter.filter_view/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/filter.ex:18: ExAdmin.Filter.filter_view/3
        web/templates/layout/admin.html.eex:40: ExAdmin.LayoutView."admin.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (myapp) lib/phoenix/router.ex:261: Myapp.Router.dispatch/2
        (myapp) web/router.ex:1: Myapp.Router.do_call/2
        (myapp) lib/myapp/endpoint.ex:1: Myapp.Endpoint.phoenix_pipeline/1
        (myapp) lib/plug/debugger.ex:93: Myapp.Endpoint."call (overridable 3)"/2
        (myapp) lib/phoenix/endpoint/render_errors.ex:34: Myapp.Endpoint.call/2
```

It looks like it's related to a model association I've built and or the data involved in a particular instance of that model, but I'm unsure what other data would be most helpful in diagnosing the issue.

**Comment by smpallen99** [comment]
Agree that more information would be helpful. I could take a look at it if I could understand how to reproduce the problem. 

I can tell from the stack trace that id_and_class_shortcuts is being called with nil for the contents param that must be a binary and that its happening on the index page since the issue is happening in view_filter which should only be used for index pages.

If you do figure out which association is causing the issue, you could post the incorrect and correct code and I'll see how I can catch the error earlier and raise a more appropriate error.

Check the fields in your call to index in the resource file. The problem is probably there. 

Steve

**Comment by romul** [comment]
@smpallen99 I think we should check type of contents inside `build_tag`, convert it to string and put a warning instead of throwing a strange mismatch error from `id_and_class_shortcuts`

```elixir
defp ensure_valid_contents(_, contents) when is_binary(contents), do: contents
defp ensure_valid_contents(_, contents) when is_list(contents), do: contents
defp ensure_valid_contents(tag_name, contents) do
  Logger.warn "#{tag_name} has been called as #{tag_name}(#{inspect(contents)}), but the first argument must be a string"
  inspect(contents)
end
```

This would help with many weird errors made by ExAdmin newcomers.

**Comment by smpallen99** [comment]
@romul If the cause of the issue is only related to a nil association, then I agree with the suggestion above. If the issue also happens with a nil derived `:name`, then I think that is something that should be rendered as `""` without an warning, since I believe that is a valid run time condition.

**Comment by romul** [comment]
@smpallen99 This issue appears not in the table with entities, but in select boxes, where you should pick entity by displayed name. So, user should define `display_name` in this case, b/c it's not possible to select a right one by "".

**Comment by smpallen99** [comment]
@romul Personally, I think we are trying to do too much here. If I’m writing a template in eex and use the `Phoenix.HTML.Form.collection` function, it renders a blank if I choose the display field that is nil. I really don’t see a difference for ex_admin provided we don’t throw an exception. It should be up to the developer to choose a field that returns a valid “name” field. So, a simple 1 line fix in Xain to allow nil would give the same experience as if manually programming a template collection. So, unless someone can convince me that ex_admin should be more intelligent, I vote on the fix in Xain. Or am I missing something?

**Comment by romul** [comment]
@smpallen99 Without any doubt this fix should be Xain.
The question is "how Xain should render non-binary content?"
For example add expected output values to each statement:
``` elixir
div(nil) #=> 

div(1) #=> 

div(true) #=> 

div do
  true
end #=> 

div do
  x = 1
end #=> 

div do
  x = 1
  1 == x
end #=> 

div do
  y = nil
end #=> 

div do
  y = nil
  nil == y
end #=> 
```

**Comment by romul** [comment]
> `Phoenix.HTML.Form.collection` function, it renders a blank if I choose the display field that is nil. I really don’t see a difference for ex_admin

The main difference is "explicit vs implicit". When you call `collection` function in template - it's explicit. 
When ex_admin generate something based on its defaults - it's implicit. In this case user doesn't even realize that `name` field is used to present resource. So, I guess if `name` field contains non-string values user should get a warning "Hey, we detect that `name` could be nil, maybe you would like to define custom `display_name` function or just set other field as `@name_column`". Maybe such the warnings should be shown only in development mode. But I'm sure that they would be helpful.

**Comment by smpallen99** [comment]
Ok, I get the implicit vs explicit argument to some extent. However, they have the option to make it explicit using `display_name`. Here is the behaviour I would like to see. If the non-binary value passed can be converted to a string with either to_string or string interpolation, then we should do that. If it can’t then we should raise a reasonable exception. Although I don’t think a log is necessary, but if you feel strongly, then it should be a :debug level log.

As for the previous question, the first three are easy:
div(nil) #=> “<div></div>"

div(1) #=> “<div>1</div>

div(true) #=> "<div>true</div>"
Its with blocks that I’m questioning the right approach. I’m leaning toward using the last statement of the block. So, that would give:
div do
  true
end #=> "<div>true</div>"

div do
  x = 1
end #=> "<div>1</div>"

div do
  x = 1
  1 == x
end #=> "<div>true</div>"

div do
  y = nil
end #=> "<div></div>"

div do
  y = nil
  nil == y
end #=> "<div>true</div>"
div do
  %{one: 1}
end #=> ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{one: 1}
    #       (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    #       (elixir) lib/string/chars.ex:17: String.Chars.to_string/1

I’m on the fence on that last exception. Perhaps we could raise a better exception that points them to the model/field that caused the error.

**Comment by romul** [comment]
> However, they have the option to make it explicit using `display_name`. 

Yeah, but they don't know about it out the box, so this awareness is a purpose of warnings (on :debug level).

> I’m leaning toward using the last statement of the block.

Hmm, and what about this test: https://github.com/smpallen99/xain/blob/master/test/xain_test.exs#L225..L232
Should it return `~s(true)`?

I think it's a little bit dizzy. Simple approach could be just concatenate all binary lines and ignore all other types. And in case when content contains only one non-binary value do `inspect(value)` and put a warning. In which cases do we need to render non-binary values? `ex_admin` doesn't need it at the moment and raise exception if it was passed, b/c it is not intended. I propose to do warning instead of exception, but not to be too much implicit by converting everything to string as though it's expected.
Besides it would be inconsistently
```elixir
div do
  "x"
  "y"
  "z"
end #=> "<div>xyz</div>"

div do
  1
  2
  3
end # =>  "<div>3</div>"
```

**Comment by smpallen99** [comment]
@romul I agree, dizzy. Just played around with the new ast design of Xain and I’m beginning to understand a little better. 

* I’m ok with the :debug warning
* I agree, block should just concat binaries
* I do want to add support for non binary tag contents in Xain. For example: 
```
  test "non binary tag contents” do
    assert div(nil) ==  ~s(<div></div>)
    assert div(1) == ~s(<div>1</div>)
    assert div(true) == ~s(<div>true</div>)
    assert div(:test) == ~s(<div>test</div>)
  end
```

**Comment by romul** [comment]
@smpallen99 Well, we are close to consensus. How about https://github.com/smpallen99/xain/pull/6/files ?
