### ISSUE TITLE
Columns containing question marks are rendered strangely

### ISSUE THREAD

**Issue by hut8** [smpallen99/ex_admin#290]
In my user model I have:

```elixir
field :admin?, :boolean
```

This results in:
![image](https://cloud.githubusercontent.com/assets/363720/22403725/24cc0688-e5ee-11e6-9ee3-cc8b29c198df.png)

**Comment by gwincr11** [comment]
@hut8 can you try my pull request version and see if it fixes your issue?

Thanks
