### ISSUE TITLE
custom filters

### ISSUE THREAD

**Issue by mithereal** [smpallen99/ex_admin#318]
i have been looking all over your docs and i dont see how to make a custom filter , i have a user  model that i want to sort by the role relation ex. can someone tell me how to do this?
`defmodule Broker.User do
  use Broker.Web, :model
  import Comeonin.Bcrypt, only: [hashpwsalt: 1]
  alias Broker.Role

  schema "users" do
    field :username, :string
    field :email, :string
    field :password_digest, :string

    timestamps()

  field :password, :string, virtual: true
  field :password_confirmation, :string, virtual: true

  has_one :profile, Broker.Profile
  belongs_to :role, Broker.Role`

`defmodule Broker.Role do
  use Broker.Web, :model

  schema "roles" do
    field :name, :string
    field :admin, :boolean, default: false

    timestamps()

    has_many :users, Broker.User

  end
`

`defmodule Broker.ExAdmin.Users do
  use ExAdmin.Register

  register_resource Broker.User do

  end
end
`
`defmodule Broker.UserController do
  use Broker.Web, :controller

  alias Broker.User

  alias Broker.Role

plug :scrub_params, "data" when action in [:create, :update]

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do

#    changeset = Guardian.Plug.current_resource(conn)
#    |> build_assoc(:profile)
#    |> User.changeset()

roles = Repo.all(Role)

 changeset = User.changeset(%User{}, _params)

    render(conn, "new.html", changeset: changeset, roles: roles)
  end`

**Comment by whitepaperclip** [comment]
Holy formatting...

@mithereal Please check the docs: https://hexdocs.pm/ex_admin/ExAdmin.Register.html#filter/2

(Typically, issue trackers are used to report bugs, not support requests.)

**Comment by whitepaperclip** [comment]
@smpallen99 Probably safe to close this.
