### ISSUE TITLE
Demo/screenshots wanted

### ISSUE THREAD

**Issue by skydan** [smpallen99/ex_admin#32]
Are you guys considering adding access to demo page or some screenshot section to increase early adopters engagement?

**Comment by cpursley** [comment]
Ditto. A live demo (or at minimum, a demo app we can pull down and run) would be really great. Screenshots would be helpful as well.

**Comment by smpallen99** [comment]
I'm thinking of doing a live demo similar to activeadmin's live demo. http://demo.activeadmin.info/admin/dashboard
Is that what you are looking for?

**Comment by cpursley** [comment]
Yes, that would rock! I'm a huge activeadmin fan and the productivity it brings and have been looking for a elixir/phoenix equivalent for some time. Thanks for the work you've put into this project.

**Comment by smpallen99** [comment]
Will try to get to it this coming week, after I get a project I started last night up and running. In the mean time, I have a demo project I've been using for testing some features on ex_admin. Its a bit of a silly example, but does work. Its configured for mysql, so you will need to change deps and config to get it working with postgres.

https://github.com/smpallen99/admin_demo

**Comment by cpursley** [comment]
Oh neat, thanks. The admin looks a whole lot like activeadmin.

**Comment by smpallen99** [comment]
I have a live demo up and running now. Check it out at [Live Demo](http://demo.exadmin.info/admin). I hope it is what you were looking for. Still more work to do on the dashboard page. Coming soon...

Note: I added a lot of new features to support this demo. Enjoy!!

**Comment by cpursley** [comment]
Thanks!
