### ISSUE TITLE
Phoenix 1.3.0-rc function MyApp.Router.Helpers.admin_path/3 is undefined

### ISSUE THREAD

**Issue by radosch** [smpallen99/ex_admin#321]
I tried to fix it for a PR, but don't know, where I would have to look further, it looks like, there must be changed some namespacing issues with ex_admin, to work with latetst phoenix version 1.3.x

I get:

```
UndefinedFunctionError at GET /admin
function MyApp.Router.Helpers.admin_path/3 is undefined (module MyApp.Router.Helpers is not available)
```

I would love to contribute, but I may need some assistance, where to look into.

**Comment by radosch** [comment]
found it:
namespacing has to be considered from new phoenix Filestructure.

    @endpoint Module.concat([@module, "Web", "Endpoint"])
    @router Module.concat([@module, "Web", "Router", "Helpers"])

cheers - raf

**Comment by MartinElvar** [comment]
Or you can just specify the module, with web.

```
config :ex_admin,
  repo: Compare.Repo,
  module: Compare.Web
```

**Comment by radosch** [comment]
Yes! Cool, that solves it the right way and is much simpler  👍 . Thanks!

**Comment by niccolox** [comment]
@radosch where you creating a new Phoenix 1.3 project or upgrading an existing one?

I am new to ExAdmin and creating a new project and having a hell of a time and would like to get a clue before I start posting

**Comment by niccolox** [comment]
I got passed basic setup issues with mix deps.clean --all
mix deps.get
mix deps.compile
mix phoenix.server

will post my 1.3 phx demo soon

**Comment by radosch** [comment]
@niccolox you may want to post to stackoverflow, thats a better ressource.

I personally have updated the 1.2.x Installation.

**Comment by niccolox** [comment]
Thanks.

I think I got it working on a new 1.3 app.

 But it was a kind of manual process. The generator seemed to not  support
1.3 ...

I did it late at night so havent got good notes. Thanjs

**Comment by fire** [comment]
```
config :ex_admin,
  repo: Example.Repo,
  module: ExampleWeb
```

For phoenix 1.3. This works after you do a 

```
mix deps.clean --all
mix deps.get
mix deps.compile
mix phoenix.server
```

Something seemed to be cached..

**Comment by peterwillcn** [comment]
phx-1.3.0-rc work,  but phx-1.3.0 release not work
