### ISSUE TITLE
How can I modify the footer?

### ISSUE THREAD

**Issue by mapeveri** [smpallen99/ex_admin#349]
Hi, How can I modify the footer?

My configurarion:

```
 config :ex_admin,
    repo: App.Repo,
    theme: ExAdmin.Theme.ActiveAdmin,
    footer_content: "Footer",
    logo_full: "<h1 class='site_title' id='site_title'>App</h1>",
    module: App,
    modules: [
        App.ExAdmin.Dashboard,
        App.ExAdmin.User
   ]
```

The property **footer_content** not working and neither **footer**.

**Comment by whitepaperclip** [comment]
The `footer` option will work. You need to restart your server after changing your config file.

**Comment by smpallen99** [comment]
Closing the issue due to lack of response from the OP
