### ISSUE TITLE
Error with hound.app

### ISSUE THREAD

**Issue by nghitran** [smpallen99/ex_admin#353]
I'm using ex_admin with github option in mix.exs. After updating ex_admin, I can no longer start my application. Got this error:

> ** (Mix) Could not start application hound: could not find application file: hound.app

The issue seems related to this #346

Because I tried using ex_admin with the commit right before #346 and it worked fine.

I don't understand why `hound` is only required in `test` environment and it still bugging me when I'm running my application in `dev` mode

**Comment by maennchen** [comment]
The only place where hound is started is test (or at least the only place I found).

https://github.com/smpallen99/ex_admin/blob/3f2563cd5a3b38f842e6e8ad1240e295a9311cb3/test/test_helper.exs#L1

Do you have a stacktrace that shows which code wants to start hound in dev?

**Comment by maennchen** [comment]
You also asked why it is only required in test.

Hound is a testing library and I see no benefit in requiring it in other envs.

**Comment by nghitran** [comment]
Hi @maennchen 

FYI, here is the output when I run `mix phoenix.server`

> [info] Application ecto exited: :stopped
> [info] Application poolboy exited: :stopped
> [info] Application decimal exited: :stopped
> [info] Application cowboy exited: :stopped
> [info] Application cowlib exited: :stopped
> [info] Application ranch exited: :stopped
> [info] Application phoenix_html exited: :stopped
> [info] Application phoenix_pubsub exited: :stopped
> 
> =INFO REPORT==== 25-Apr-2017::16:51:03 ===
>     application: logger
>     exited: stopped
>     type: temporary
> ** (Mix) Could not start application hound: could not find application file: hound.app

I don't know how to get more debug info than this, so if you know any more steps that I can do to help getting more detail about this issue, I'll be more than happy following the instructions.

**Comment by nghitran** [comment]
Hi,

Sorry, I found the issue, it was my mistake. I accidentally put `hound` in my `applications` list. So this issue report is invalid. 😅

Thanks for your support @maennchen

**Comment by smpallen99** [comment]
@nghitran Thanks for letting us know.
