### ISSUE TITLE
Filter by and association field?

### ISSUE THREAD

**Issue by supercodepoet** [smpallen99/ex_admin#354]
Is there a way to filter by and association field? Say I have an Order with a User. I want to filter Orders index by the User.email. Is this possible?

**Comment by smpallen99** [comment]
that was quick, did you find it?

**Comment by supercodepoet** [comment]
Sorry, no I did not find it but I was stupid and didn't read the guidelines so I closed this issue and posted the question to the mailing list. Sorry about that.
