### ISSUE TITLE
Changing the navigation links

### ISSUE THREAD

**Issue by ben-ward** [smpallen99/ex_admin#357]
Currently I've got a large set of over a million records that takes a long time to even load the first page. I was looking for a way to set a default filter to something like name is "ChangeThisValue" just so I could load the page and let someone search using the filters.

I was able to make a default scope with no records. However, any searches will only be within that scope.

Is there another way to short circuit the initial load on index?
The link below will work but I would need to change the link in the navigation.

http://localhost:3000/exadmin/people?q%5Bname_equals%5D=ChangeThisValue

Thanks,
Ben

**Comment by smpallen99** [comment]
I presume the loading time is with the filter and not the main index page. Correct? 

There is no built in way of doing this. If you want to override the index page, you could extend the menu macro to allow providing  a query parameter. 

However, if its the filter stuff that is creating an issue then we should look at how it can be optimized. Can you identify the areas of the filters handlers that are problematic and what you recommend to optimize, I can help you with the PR.

One last though... If you just want to override the main menu nav items, you might be able to disable them `menu false` I believe, and add your own that contains the appropriate query.

**Comment by ben-ward** [comment]
Thanks. I will try those and report back.

**Comment by ben-ward** [comment]
Thanks for your help! I ended up getting decent results with lowering the number of things I filter on and the number of columns I show.


 register_resource Project.People do
    filter [:id, :name, :url]

    index do
      selectable_column()

      column :id
      column :name
      column :url
      actions()     # display the default actions column
    end

Thanks again for a great tool. I used ActiveAdmin in Rails and it immediately makes sense here.
