### ISSUE TITLE
Creating new (coherence) user in ex_admin

### ISSUE THREAD

**Issue by tmbb** [smpallen99/ex_admin#364]
I'd like to create new coherence users from the admin interface.
I have everything set up correctly and I can already create users using the forms.
However, I'd like to confirm those users immediately when they are created, instead of sending the confirmation link (which is not even sent in this case, as it bypasses most of coherence's pipeline).
Is this possible? Could you send me some pointers on how to achieve it?

The obvious way would be to use `Coherence.ControllerHelpers.confirm!` on the changeset after inserting it, but I don't know how to do inject this function into `ExAdmin`'s pipeline.

**Comment by smpallen99** [comment]
Take a look at the [after_filter](https://github.com/smpallen99/ex_admin/blob/master/lib/ex_admin/register.ex#L433). It should give you exactly what your looking for. You'll get the resource as a parameter and be able to call the Coherence `confirm` function on it. BTW, `confirm/1` takes the user schema and not a changeset.

**Comment by tmbb** [comment]
Thanks! That's exactly what I needed.

I've written a pull request with updates to the ExDocs of `Register.after_filter` in which:

1) I try to clarify a little the fact that `resources` is a schema (it was not very clear before)

2) I add some text explaining how the filter might be useful when using ExAdmin to add users to a web application (without mentioning coherence, which is a completely separate application and shouldn't be mixed with ExAdmin).

While this is certainly a very specific use case, I think many new users will appreciate the guidance on this topic. Feel free to refuse the pull request if you think the ExDocs are the wrong place to write about this.
