### ISSUE TITLE
Validation on changeset triggered when navigating to the form

### ISSUE THREAD

**Issue by ciokan** [smpallen99/ex_admin#368]
I have a custom validator in place for one of the models and an admin page for it but, whenever I navigate to the `new` endpoint, that validation is triggered without me submitting anything - it can't even reach the form because of this error:

```
web_1         | Request: GET /admin/docker_images/new
web_1         | ** (exit) an exception was raised:
web_1         |     ** (ArgumentError) cannot perform Heroico.Repo.get/2 because the given value is nil
web_1         |         (ecto) lib/ecto/repo/queryable.ex:314: Ecto.Repo.Queryable.query_for_get/3
web_1         |         (ecto) lib/ecto/repo/queryable.ex:48: Ecto.Repo.Queryable.get/5
web_1         |         (heroico) web/models/docker_image.ex:56: Heroico.DockerImage.validate_image/1
web_1         |         web/controllers/admin_resource_controller.ex:66: ExAdmin.AdminResourceController.new/3
web_1         |         web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
web_1         |         web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
...
```

`validate_image` is simply looking for a parent record (where it fails):

	defp validate_image(changeset) do
		registry_id = get_field(changeset, :docker_registry_id)
		image = get_field(changeset, :image)
		tag = get_field(changeset, :tag)

		registry = Repo.get(Heroico.DockerRegistry, registry_id)

		case image_exists(image, tag, registry.host, registry.username, registry.password) do
			{:error, error_message} -> add_error(changeset, :image, error_message)
			{:ok} -> changeset
		end

	end

but it's not supposed to fire unless I hit "Submit". It looks like `web/controllers/admin_resource_controller.ex:66` is triggering the validation on an empty changeset. Any ideas?

**Comment by smpallen99** [comment]
ExAdmin is going to call your changset/1 for the new action. So, your validator should only be executed if its a change action. You can check for `%Ecto.Changeset{data: %{id: id}} when not is_nil(id)` to run your validator.
