### ISSUE TITLE
Logout of ExAdmin

### ISSUE THREAD

**Issue by th31nitiate** [smpallen99/ex_admin#369]
I don't if we can consider this an issue. I am unable to perform logout function from admin. I think users have to move to alternative pages to shutdown or cookies are cleared at browser shutdown.

I was wondering if anyone has an idea on how to enable coherence to log out from within ExAdmin. I have been attempting to customize the nav bar but the struct is a bit different. It would have been cool if I could embed my general app layout into ExAdmin.

(If I can help with any dev or feature implementation feel free to let me know. I am at a low level with elixir though so guidance would be required to get started. Once I am up running all should be well.)

**Comment by smpallen99** [comment]
Could be a problem with your implementation of the `ExAdmin.Authentication` protocol. Could also be a routing issue. What is the error? 

Yes, I will be looking for some help fairly soon. Check out #333 to get a sense of the stuff I just started to work on. Once I get the new architecture sketched out, I'll be open to contributions from the community. Please feel free to comment on the issue if you have ideas.

**Comment by th31nitiate** [comment]
Thanks for your input.
