### ISSUE TITLE
ExAdmin assets won't server over https

### ISSUE THREAD

**Issue by RobinClowers** [smpallen99/ex_admin#372]
I just updated to 4d4a5b374c05f641f5a1d20536bf5c95f68b41bd, and now I get insecure content warnings for the stylesheets and scripts.

**Comment by RobinClowers** [comment]
Possible that https://github.com/smpallen99/ex_admin/pull/315 is the culprit?

**Comment by th31nitiate** [comment]
Are you using a load balancer or reverse proxy to server content from phoenix?

If this occurred after an update then I would recommend revert back and check to see if the issue resolves.

**Comment by RobinClowers** [comment]
@th31nitiate I host on Heroku, using the [Phoenix static buildpack](https://github.com/gjaldon/heroku-buildpack-phoenix-static). Yes, this is definitely because I updated ExAdmin, so clearly it's a bug...

**Comment by th31nitiate** [comment]
Ok, no probs. Can you help with instruction on how to reproduce the issue or can you grab a Chrome dev tools HAR recording so that we can review where the main fault might be occurring.

I can try it with a test account then we will be able to better pinpoint where the bug might be.

Have you managed to perform a roll back for the app so at least it usable in the mean time?

**Comment by smpallen99** [comment]
@th31nitiate Thanks for the support on this issue. You rock!!

**Comment by RobinClowers** [comment]
@th31nitiate it's on a staging environment, so I haven't reverted. I've attached a HAR, you can see that the admin_lte2.css and jquery.min.js loaded over http, even though everything else is https. When I view the page source, I can see that those assets are specified with full urls, not just absolute paths. I believe this change was a result of https://github.com/smpallen99/ex_admin/pull/315.


[smart-services-staging.herokuapp.com.har.zip](https://github.com/smpallen99/ex_admin/files/1011741/smart-services-staging.herokuapp.com.har.zip)

**Comment by RobinClowers** [comment]
I figured this out, I was just missing a Phoenix.Endpoint configuration.

```elixir
config :smart_services, SmartServices.Endpoint,
  url: [host: System.get_env("HOST"), scheme: "https", port: 443]
```
