### ISSUE TITLE
Checkboxes in a form for many_to_many association

### ISSUE THREAD

**Issue by airled** [smpallen99/ex_admin#377]
Hi there. Maybe I missed something but I have an issue:
I have User and Group models. They're connected through `many_to_many` association via "groups_users"-table (no model for this one).
```
  schema "users" do
    ...
    many_to_many :groups, MyApp.Group, join_through: "groups_users", on_replace: :delete
    ...
  end
```

```
  schema "groups" do
    ...
    many_to_many :users, MyApp.User, join_through: "groups_users"
    ...
  end
```

On User admin page I want to be able to match user to several groups, so I use checkboxes in my form:
```
    form user do
      inputs do
       ...
      end
      inputs "Groups" do
        inputs :groups, as: :check_boxes, collection: Repo.all(MyApp.Group)
      end
    end
```
There is no problem when I check some groups and save a user. Associations saved properly. But when I open edit-page of user with groups, all chekboxes are empty. If I don't want to lose user's groups I should check it every time when I edit user. Is there a way to tell ExAdmin to automatically check user's groups on edit page?

**Comment by c6p** [comment]
I had the same problem. I guess ExAdmin preloads `belongs_to` fields by default but not `many_to_many`. If you want ExAdmin to prefill them, you need to modify [query options](https://hexdocs.pm/ex_admin/ExAdmin.Register.html#query/1). For example:

    query do
      %{edit: [preload: [:groups]] }
    end

**Comment by airled** [comment]
Well, yes. Looks like `query` is all I need, but it raises:
`function Ecto.Association.NotLoaded.__schema__/1 is undefined or private`.

**Comment by airled** [comment]
@c6p Yes! Thank you so much for helping. `query` works perfectly. My bad that I didn't see it in docs.
