### ISSUE TITLE
mix deps.compile failing on Phoenix 1.3

### ISSUE THREAD

**Issue by ronyv89** [smpallen99/ex_admin#396]
I've tried to add ex_admin package from the github master branch in my **Phoenix 1.3** project.
My app name is Quest. In the installation docs, it is mentioned to config module as Quest.Web, which is something that doesn't exist(Is it supposed to be **QuestWeb**?).
When I try to do **mix do deps.get, deps.compile**, It fails with a message:
```warning: the dependency :phoenix_html is duplicated at the top level, please remove one of them```

**mix admin.install** also fails, with the following error:
```** (Mix) Can't find brunch-config.js```
Please help.

**Comment by Focinfi** [comment]
Use **Phoenix1.2** or wait the author to upgrade this project.

`ex_admin-0.8` is incompatible with Phoenix1.3 cause the Phoenix1.3 changed the directory structure a lot, like spliting `web/*` into `/assets` and `lib/app_web`, so the `./brunch-config.js` has been moved to `./assets/find brunch-config.js`.

**Comment by ronyv89** [comment]
I thought the **master** branch was updated for Phoenix 1.3

**Comment by Focinfi** [comment]
I don't think so, [this line of code](https://github.com/smpallen99/ex_admin/blob/master/lib/mix/tasks/admin.install.ex#L77) still try to find the `./brunch-config.js` instead of `./assets/find brunch-config.js`.

**Comment by ronyv89** [comment]
Closing this since **phx-1.3** branch works
