### ISSUE TITLE
Installation fails with Internal consistency check failed

### ISSUE THREAD

**Issue by haslinger** [smpallen99/ex_admin#411]
I am trying to install ex_admin following step by step the installation section on Github using _GitHub with Ecto 2.0_

The step `mix do deps.get, deps.compile` fails with

```
== Compilation error in file lib/ex_admin/gettext.ex ==
** (CompileError) Elixir.ExAdmin.Gettext: function lgettext/4+1688:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_match_string,{f,561},[{x,6},48,{string,"rofile"}]}
  Error:       {no_bsm_context,{x,6}}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
I am runnning:
* Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
* Elixir 1.5.2
* Phoenix 1.3.0

If I can provide any useful information or if I should instead use talon, please let me now.

**Comment by StephanMeijer** [comment]
Duplicate of: https://github.com/smpallen99/ex_admin/issues/408

**Comment by haslinger** [comment]
Right, sorry,  then let's close this here.
