### ISSUE TITLE
Links not displaying properly

### ISSUE THREAD

**Issue by MattGaud2425** [smpallen99/ex_admin#457]
receiving the raw html instead of the actual links. 

when i click new game it gives me an argument error. not sure what the cause is.

**Comment by mattgaudio** [comment]
a href='/admin/games/3' class='member_link view_link' title='View'>View</a><a href='/admin/games/3/edit' class='member_link edit_link' title='Edit'>Edit</a><a href='/admin/games/3' class='member_link delete_link' data-confirm='Are you sure you want to delete this?' data-remote='true' data-method='delete' data-params='page=1' rel='nofollow' title='Delete'>Delete</a

**Comment by mattgaudio** [comment]
<a href='/admin/games/3'>3</a>

**Comment by MattGaud2425** [comment]
![screenshot-phoenix local-4000-2018 12 24-05-45-43](https://user-images.githubusercontent.com/5988010/50397548-40064e80-073f-11e9-9dde-1edfd3e00aaa.png)
![screenshot-phoenix local-4000-2018 12 24-05-46-09](https://user-images.githubusercontent.com/5988010/50397549-40064e80-073f-11e9-8af1-9a8f827f4ebe.png)

**Comment by MattGaud2425** [comment]
[error] %ArgumentError{message: "argument error"}
[error] [{:erlang, :bit_size, [:safe], []}, {ExAdmin.Theme.AdminLte2.Form, :"-form_box/3-fun-0-", 2, [file: 'lib/ex_admin/themes/admin_lte2/form.ex', line: 148]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {ExAdmin.Theme.AdminLte2.Form, :form_box, 3, [file: 'lib/ex_admin/themes/admin_lte2/form.ex', line: 145]}, {ExAdmin.Form, :"-build_main_block/4-fun-0-", 6, [file: 'lib/ex_admin/form.ex', line: 552]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {ExAdmin.Form, :build_main_block, 4, [file: 'lib/ex_admin/form.ex', line: 550]}, {ExAdmin.Theme.AdminLte2.Form, :build_form, 6, [file: 'lib/ex_admin/themes/admin_lte2/form.ex', line: 24]}, {ExAdmin.AdminResourceController, :new, 3, [file: 'web/controllers/admin_resource_controller.ex', line: 70]}, {ExAdmin.AdminResourceController, :action, 2, [file: 'web/controllers/admin_resource_controller.ex', line: 1]}, {ExAdmin.AdminResourceController, :phoenix_controller_pipeline, 2, [file: 'web/controllers/admin_resource_controller.ex', line: 1]}, {MythicWeb.Endpoint, :instrument, 4, [file: 'lib/mythic_web/endpoint.ex', line: 1]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 278]}, {MythicWeb.Endpoint, :plug_builder_call, 2, [file: 'lib/mythic_web/endpoint.ex', line: 1]}, {MythicWeb.Endpoint, :"call (overridable 3)", 2, [file: 'lib/plug/debugger.ex', line: 122]}, {MythicWeb.Endpoint, :call, 2, [file: 'lib/mythic_web/endpoint.ex', line: 1]}, {Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/cowboy/handler.ex', line: 18]}, {:cowboy_protocol, :execute, 4, [file: '/app/deps/cowboy/src/cowboy_protocol.erl', line: 442]}]
[info] Sent 500 in 825ms
[error] #PID<0.887.0> running MythicWeb.Endpoint (cowboy_protocol) terminated
Server: phoenix.local:4000 (http)
Request: GET /admin/games/new
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.bit_size(:safe)
        (ex_admin) lib/ex_admin/themes/admin_lte2/form.ex:148: anonymous fn/2 in ExAdmin.Theme.AdminLte2.Form.form_box/3
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/themes/admin_lte2/form.ex:145: ExAdmin.Theme.AdminLte2.Form.form_box/3
        (ex_admin) lib/ex_admin/form.ex:552: anonymous fn/6 in ExAdmin.Form.build_main_block/4
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_admin) lib/ex_admin/form.ex:550: ExAdmin.Form.build_main_block/4
        (ex_admin) lib/ex_admin/themes/admin_lte2/form.ex:24: ExAdmin.Theme.AdminLte2.Form.build_form/6
        (ex_admin) web/controllers/admin_resource_controller.ex:70: ExAdmin.AdminResourceController.new/3
        (ex_admin) web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.action/2
        (ex_admin) web/controllers/admin_resource_controller.ex:1: ExAdmin.AdminResourceController.phoenix_controller_pipeline/2
        (mythic) lib/mythic_web/endpoint.ex:1: MythicWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (mythic) lib/mythic_web/endpoint.ex:1: MythicWeb.Endpoint.plug_builder_call/2
        (mythic) lib/plug/debugger.ex:122: MythicWeb.Endpoint."call (overridable 3)"/2
        (mythic) lib/mythic_web/endpoint.ex:1: MythicWeb.Endpoint.call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by kagux** [comment]
@mattgaudio how did you resolve the issue?
