### ISSUE TITLE
Map datatype crashed

### ISSUE THREAD

**Issue by OvermindDL1** [smpallen99/ex_admin#47]
As mentioned in #42 you had not used the Ecto Map datatype yet, and although ex_admin displays it fine it crashes when attempting to edit it:

```elixir
[info] GET /admin/extra_datas/bdf0e6af-6571-47f5-9df1-97892b9ad228/edit
[debug] Processing by ExAdmin.AdminController.edit/2
  Parameters: %{"id" => "bdf0e6af-6571-47f5-9df1-97892b9ad228", "resource" => "extra_datas"}
  Pipelines: [:browser]
[debug] SELECT e0."id", e0."data", e0."user_session_id", e0."inserted_at", e0."updated_at" FROM "extradatas" AS e0 WHERE (e0."id" = $1) [<<189, 240, 230, 175, 101, 113, 71, 245, 157, 241, 151, 137, 43, 154, 210, 40>>] OK query=1.1ms
[debug] SELECT u0."id", u0."session_id", u0."user_id", u0."inserted_at", u0."updated_at" FROM "user_sessions" AS u0 WHERE (u0."id" IN ($1)) [<<111, 91, 24, 99, 183, 37, 74, 61, 174, 242, 237, 33, 60, 195, 68, 208>>] OK query=0.9ms
[debug] SELECT u0."id", u0."session_id", u0."user_id", u0."inserted_at", u0."updated_at" FROM "user_sessions" AS u0 [] OK query=0.8ms
[error] %Protocol.UndefinedError{description: nil, protocol: String.Chars, value: %{"extra_test_data" => 42}}
[error] [{String.Chars, :impl_for!, 1, [file: 'lib/string/chars.ex', line: 3]}, {String.Chars, :to_string, 1, [file: 'lib/string/chars.ex', line: 17]}, {Xain, :"-open_tag/3-fun-0-", 2, [file: 'lib/xain.ex', line: 88]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1473]}, {Xain, :open_tag, 3, [file: 'lib/xain.ex', line: 88]}, {ExAdmin.Form, :build_control, 7, [file: 'lib/ex_admin/form.ex', line: 870]}, {ExAdmin.Form, :_wrap_item, 7, [file: 'lib/ex_admin/form.ex', line: 617]}, {ExAdmin.Form, :wrap_item, 8, [file: 'lib/ex_admin/form.ex', line: 580]}, {ExAdmin.Form, :"-build_item/5-fun-9-", 6, [file: 'lib/ex_admin/form.ex', line: 804]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1473]}, {ExAdmin.Form, :build_item, 5, [file: 'lib/ex_admin/form.ex', line: 803]}, {ExAdmin.Form, :"-build_main_block/4-fun-0-", 6, [file: 'lib/ex_admin/form.ex', line: 532]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1473]}, {ExAdmin.Form, :build_main_block, 4, [file: 'lib/ex_admin/form.ex', line: 531]}, {ExAdmin.Form, :build_form, 5, [file: 'lib/ex_admin/form.ex', line: 464]}, {ExAdmin.AdminController, :edit, 2, [file: 'web/controllers/admin_controller.ex', line: 178]}, {ExAdmin.AdminController, :action, 2, [file: 'web/controllers/admin_controller.ex', line: 1]}, {ExAdmin.AdminController, :phoenix_controller_pipeline, 2, [file: 'web/controllers/admin_controller.ex', line: 1]}, {ForgeStats.Router, :dispatch, 2, [file: 'lib/phoenix/router.ex', line: 261]}, {ForgeStats.Router, :do_call, 2, [file: 'web/router.ex', line: 1]}]
[info] Sent 500 in 65ms
[error] #PID<0.476.0> running ForgeStats.Endpoint terminated
Server: files.minecraftforge.net:4001 (http)
Request: GET /admin/extra_datas/bdf0e6af-6571-47f5-9df1-97892b9ad228/edit
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{"extra_test_data" => 42}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        lib/xain.ex:88: anonymous fn/2 in Xain.open_tag/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/xain.ex:88: Xain.open_tag/3
        lib/ex_admin/form.ex:870: ExAdmin.Form.build_control/7
        lib/ex_admin/form.ex:617: ExAdmin.Form._wrap_item/7
        lib/ex_admin/form.ex:580: ExAdmin.Form.wrap_item/8
        lib/ex_admin/form.ex:804: anonymous fn/6 in ExAdmin.Form.build_item/5
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/form.ex:803: ExAdmin.Form.build_item/5
        lib/ex_admin/form.ex:532: anonymous fn/6 in ExAdmin.Form.build_main_block/4
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/form.ex:531: ExAdmin.Form.build_main_block/4
        lib/ex_admin/form.ex:464: ExAdmin.Form.build_form/5
        web/controllers/admin_controller.ex:178: ExAdmin.AdminController.edit/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (forgestats_app) lib/phoenix/router.ex:261: ForgeStats.Router.dispatch/2
        (forgestats_app) web/router.ex:1: ForgeStats.Router.do_call/2
```

For note, the Map datatype maps to the PostgreSQL JSONB datatype, a fully indexable on any query binary JSON database, so displaying it in a JSON editor would probably make the most sense.  Also filtering queries on it can be *very* advanced by being able to query about any part of the structure very efficiently, so it has quite good uses.  In MariaDB it maps to a binary I think, still JSON though, just lacking the advanced querying abilities and no field indexing.

Test URL:  http://files.minecraftforge.net:4001/admin/extra_datas/bdf0e6af-6571-47f5-9df1-97892b9ad228/edit

**Comment by smpallen99** [comment]
I can't find any information on how phoenix handles map types. Furthermore, I tried to create a model with map type using `phoenix.gen.html Info infos ref data:map`. 

The migrations work, but the scaffolding does not work. 

So, I will have an issue adding support in ExAdmin until I figure out how to use the fields in a basic Phoenix app. Can you provide an example of using maps in index, show, edit pages?

**Comment by smpallen99** [comment]
@OvermindDL1 Here is how I'm thinking of handling map types, and any other unknown type. What do you think?

* Index page - if the term is unprintable, do an inspect on it
* Show page - same. if unprintable, do an inspect on it
* Form page - if unknown type, print the field only, don't allow it to be edited.

I suppose, if it is a map, I would render a form field for every field in the map. This will take a bit more work, but might not be too difficult.

Thoughts?

**Comment by OvermindDL1** [comment]
Well the Map datatype in Ecto is actually quite literally an Elixir Map datatype ${}.  See http://elixir-lang.org/docs/stable/elixir/Map.html for details.  So as long as it supports those then it should be able to do anything.  Maps are definitely unprintable by default, but if you use, say, the [Poison](https://github.com/devinus/poison) library (the most common JSON library for Elixir/Phoenix) then you can easily convert any normal Elixir Map into JSON and back again, especially as that is precisely what Ecto does internally to convert Elixir Maps to/from JSON in the database.  :-)

Really though, if you changed to using [Elixir Protocols](http://elixir-lang.org/getting-started/protocols.html) as should probably be done for such things then you can add defimpl's for the protocol to define all the normal Ecto database types for printing, converting, etc...  Plus then people could add their own custom database types just by defimpl'ing the protocol to fulfill the requirements, which would then work transparently with your system, no 'inspect'ing needed or anything.  You could even have the protocol supply form elements so if someone stores, say, GPS coords in a PostgreSQL GIS entry then they could have custom form elements to handle it.  Elixir Protocols should be used for all such interaction points and adding default implementations for all the default Ecto types would support 99% of all cases.  :-)

**Comment by smpallen99** [comment]
Protocols... Good idea. I'll take a look at that. Thanks

**Comment by smpallen99** [comment]
I'm just about to submit an update that handles the displaying the map fields. However, it will be much more difficult to automatically decode the form data during an :create or :update. You can use a controller before filter. For example:

```Elixir
      register_resource AdminIdIssue.UserSession do
        controller do
          before_filter :decode, only: [:update, :create]

          def decode(conn, params) do
            if get_in params, [:usersession, :data] do
              params = update_in params, [:usersession, :data], &(Poison.decode!(&1))
            end
            {conn, params}
          end
        end
      end
```

I've updated the docs in `lib/ex_admin/ex_admin.ex` to explain how to add new type renderers.

**Comment by OvermindDL1** [comment]
Very nice!  Will examine shortly.  Thanks much!  ^.^
