### ISSUE TITLE
binary_id issue

### ISSUE THREAD

**Issue by sobolevn** [smpallen99/ex_admin#57]
There's an issue when working with `binary_id`. I guess it happens when trying to convert in to `int` somewhere in the code. Here's the exception message:

> Postgrex expected an integer in -2147483648..2147483647 that can be encoded/cast to type "int4", got &lt;&lt;190, 171, 222, 121, 147, 77, 77, 185, 186, 87, 17, 70, 193, 192, 41, 66&gt;&gt;. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.

Full trace:

<img width="1280" alt="2016-04-23 13 37 04" src="https://cloud.githubusercontent.com/assets/4660275/14760899/d7b68d2c-0958-11e6-80d6-1a2d0328967f.png">

My thoughts: 

<img width="1005" alt="2016-04-23 13 37 28" src="https://cloud.githubusercontent.com/assets/4660275/14760896/c7272958-0958-11e6-8251-593c41468d84.png">

I guess, that it receives the `<option>`'s value and expects it to be `int`. It fails when it is binary.

**Comment by smpallen99** [comment]
@sobolev I have not worked much with binary ids. Can you provide some models a migrations that will reproduce the issue? Should not be difficult to fix once I have a setup to reproduce.

**Comment by sobolevn** [comment]
Sorry, the issue was with my custom controller.

**Comment by smpallen99** [comment]
I did find an issue with my testing of a model with a binary foreign key with all defaults:

```
[error] #PID<0.733.0> running Binaryid.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin/posts
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Xain.Helpers.id_and_class_shortcuts/2
        lib/xain/helpers.ex:41: Xain.Helpers.id_and_class_shortcuts(nil, [value: ""])
        lib/ex_admin/filter.ex:150: anonymous fn/3 in ExAdmin.Filter.build_field/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/filter.ex:148: ExAdmin.Filter.build_field/3
        lib/ex_admin/filter.ex:25: anonymous fn/4 in ExAdmin.Filter.filter_view/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/ex_admin/filter.ex:25: ExAdmin.Filter.filter_view/3
        web/templates/layout/admin.html.eex:46: ExAdmin.LayoutView."admin.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (binaryid) lib/phoenix/router.ex:261: Binaryid.Router.dispatch/2
        (binaryid) web/router.ex:1: Binaryid.Router.do_call/2
        (binaryid) lib/binaryid/endpoint.ex:1: Binaryid.Endpoint.phoenix_pipeline/1
        (binaryid) lib/plug/debugger.ex:93: Binaryid.Endpoint."call (overridable 3)"/2
        (binaryid) lib/phoenix/endpoint/render_errors.ex:34: Binaryid.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by smpallen99** [comment]
Looks like its not an issue. I missed the blog_id in my model's @required_fields. Works fine after adding that.
