### ISSUE TITLE
Model w/ out 'id' field breaks by default, because of Sorting

### ISSUE THREAD

**Issue by jeffdeville** [smpallen99/ex_admin#63]
I have a table w/out a autoincrementing id field, and it fails w/ the following error:

deps/ex_queb/lib/ex_queb.ex:120: field `App.MyModel.id` in `order_by` does not exist in the model source in query

Is there a place to override the default order by field by any chance?

**Comment by smpallen99** [comment]
@jeffdeville No option or workaround that I can think of. I'll try to get it fixed today.

**Comment by jeffdeville** [comment]
Wow, that'd be awesome, thank you!  Seems like the problem is in ex_queb/lib/ex_queb.ex:122. It assumes an id field. I'd be happy to try and help, but I'm stuck at the moment understanding how this code doesn't blow up, because 'c' isn't defined anywhere. Just getting back into elixir, so I'm afraid I'm not as helpful as I'd like.

**Comment by smpallen99** [comment]
@jeffdeville think of c as a variable used in the macro `from`, which gets set to the item in the query so you can do something like `c.id` to refer to a specific field. 

Currently, I have a test passing that derives the correct primary field from the schema. I need to add some edge cases. I also want to add something to override the default sort field. With this, you will be able to set the field and avoid any edge cases I might miss with the auto detection code.

**Comment by smpallen99** [comment]
@jeffdeville still working on this fix, but is a large change. many different parts of ex_admin assume id key...

**Comment by smpallen99** [comment]
@jeffdeville Just pushed fix to branch v0.7.3. Make sure your project gets ex_queb  github:
``` 
  {:ex_queb, github: "smpallen99/ex_queb", override: true}
```

Let me know how it works.

**Comment by smpallen99** [comment]
I should leave this open until I port to master branch.

**Comment by jeffdeville** [comment]
So far so good, I'll continue playing w/ it though, as I see you made some big changes.  Thanks Steve!

For anyone else who may be looking, this is what I changed my deps to:

{:ex_queb, github: "E-MetroTel/ex_queb", override: true},
{:ex_admin, github: "smpallen99/ex_admin", branch: "v0.7.3", override: true},
