### ISSUE TITLE
Integer field filter search shows result by first option only

### ISSUE THREAD

**Issue by piyushchauhan2011** [smpallen99/ex_admin#64]
![screen shot 2016-04-25 at 6 01 27 pm](https://cloud.githubusercontent.com/assets/693487/14777377/0438cb22-0b10-11e6-846f-602a8483c363.png)

When I select `greater than` option in select menu, it default backs to `equal to` and search using that.

**Comment by smpallen99** [comment]
This is a duplicate of #61 which has been fixed. Thansk
