### ISSUE TITLE
`column` label with spaces error

### ISSUE THREAD

**Issue by sobolevn** [smpallen99/ex_admin#68]
This is easy to fix, I guess. 

I have a code like this:

    panel "Registrations" do
        table_for event.registrations do
          column "Full name", fn(item) -> text full_name(item) end
          column "Email", fn(item) -> text item.email end
        end
      end

Which produces this broken output:

<img width="737" alt="2016-04-27 15 19 19" src="https://cloud.githubusercontent.com/assets/4660275/14851903/a1d3bbcc-0c8b-11e6-9d61-e2d349da9113.png">

And when I change it to `Fullname`, like this:

    panel "Registrations" do
        table_for event.registrations do
          column "Full name", fn(item) -> text full_name(item) end
          column "Email", fn(item) -> text item.email end
        end
      end

It works normally:

<img width="719" alt="2016-04-27 15 19 39" src="https://cloud.githubusercontent.com/assets/4660275/14851920/bd304fac-0c8b-11e6-8761-0517356588c1.png">

**Comment by smpallen99** [comment]
Issue resolved on v0.7.3 and master. Used the wrong issue number in the commits. See issue #69 for the commits that fix this issue.
