### ISSUE TITLE
Internal server error on missing id

### ISSUE THREAD

**Issue by sobolevn** [smpallen99/ex_admin#74]
I have faced a small issue with the urls. Here's what I am talking about:

If you try to visit http://demo.exadmin.info/admin/orders/100500 (or generally any link with non-existing id) it will fail with the server error and 500 status. Like:

> http://demo.exadmin.info/admin/orders/100500 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

But it's expected to return 404 status.

Here's what happens with debug turned on:

> UndefinedFunctionError at GET /admin/speakers/100500
> undefined function nil.id/0

I can help with this one, if needed.

**Comment by smpallen99** [comment]
@sobolevn, I would appreciate the help. I'd like to see the fix in v0.7.3 branch and master if you could.

**Comment by sobolevn** [comment]
How do you think this should be implemented?

I have figured out, that the error occurs in these lines: https://github.com/smpallen99/ex_admin/blob/2344daecc2dc41623ec806d804ab8d471cb0f568/web/controllers/admin_controller.ex#L159

The smallest fix I did was:

    if resource == nil do
        throw :invalid_route
    end

But I guess it should be implemented in a standard `Phoenix`-way with custom `Error` view and custom exception for the `Plug.Exception` protocol.

Does this also applies to the following situation? 

> http://127.0.0.1:4000/admin/speaker Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Here we can use https://hexdocs.pm/phoenix/Phoenix.Router.NoRouteError.html

**Comment by sobolevn** [comment]
Or something like the following: https://github.com/phoenixframework/phoenix/blob/e3c23a364af4f2283e2498fdb47c60161f262a1f/lib/phoenix/endpoint/render_errors.ex

**Comment by smpallen99** [comment]
I'm wondering if we should render 404/500 with projects main Error View? If the wrong resource is give, or the record could not be found, render the 404. Other erorrs will automatically render the 500. I'm not exactly sure how the 404 gets rendered on a regular phoenix project, but should be pretty easy to figure out. Phoenix must wrap the action in a try block and send the 404 for a `Ecto.NoResultsError` exception.

I supposed we this would just work as long as the ExAdmin code raises that exception on the Repo.get/one...

**Comment by sobolevn** [comment]
Ready to be closed?

**Comment by smpallen99** [comment]
I'll merge it into master then close it.

**Comment by smpallen99** [comment]
merged in master
