### ISSUE TITLE
JQuery Error with Delete action in Safari

### ISSUE THREAD

**Issue by bsidoruk** [smpallen99/ex_admin#86]
When I run ExAdmin in my project I noticed that I'm getting this JQuery error in web inspector in regards to the delete actions: 
    
    Error: Syntax error, unrecognized expression: a[data-method='delete'
    
I checked out your example project and noticed the same error.  When you try to delete in the index page, it redirects to the show. From there the delete just reloads the page.

**Comment by smpallen99** [comment]
what version of ex_admin are you using?

**Comment by bsidoruk** [comment]
I was using 0.7.2, but I tried adding your themes branch to mix.exs(as it seemed to be the most recently updated) and it was still having this issue.

**Comment by bsidoruk** [comment]
I just tried this out in Firefox, and it seems to work there, so it looks like it may be a Safari only issue

**Comment by smpallen99** [comment]
Agree. I just confirmed the issue on safari. I'll add it to my backlog. Thanks...

**Comment by bsidoruk** [comment]
Thanks for looking into it

**Comment by romul** [comment]
Works for me. Looks like it was fixed.
