### ISSUE TITLE
Master branch have some dependencies issues on Ecto 2.0

### ISSUE THREAD

**Issue by romul** [smpallen99/ex_admin#88]
Some of dependencies are still locked to 1.x version of Ecto:

```
* ecto (Hex package)
  the dependency ecto

  > In mix.exs:
    {:ecto, "~> 2.0.0-rc.4", [hex: :ecto, manager: :mix]}

  does not match the requirement specified

  > In deps/ex_queb/mix.exs:
    {:ecto, "~> 1.1", [optional: false, hex: :ecto]}

  > In deps/scrivener/mix.exs:
    {:ecto, "~> 1.0", [optional: false, hex: :ecto]}

```

**Comment by smpallen99** [comment]
I'll open an issue on ex_queb and fix it in master. I'll update the the deps in ex_admin to point to github version of ex_queb. 

I'm not sure I can do anything with scrivener yet, but I'll post an issue there. 

In the mean time, you can get around this by adding override: true on the deps in your main project file. 

Always a pain managing deps on around beta and rc versions of dependencies. :(

Steve

**Comment by romul** [comment]
@smpallen99 Yeah, you are right. Thanks for the quick response.
