### ISSUE TITLE
Route integration should support adding additional plugs

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/ex_admin#9]
Cannot easily add an auth plug to the route macro. Need to change this design so it integrates with other pipelines in the application's router.ex file

**Comment by r-icarus** [comment]
Is there currently a way to add a plug?

**Comment by smpallen99** [comment]
There is support for adding controller plugs in the register_resource DSL. However, I don't yet have support for adding a router plug. If you want to add a router plug, then find the ExAdmin.Router in the your deps directory, and copy over the admin_routes macro code (the pipeline :admin and scope ... code).

See the docs in ExAdmin.Register for an example of adding a controller plug: 

```
    controller do
        plug :my_plug, the_answer: 42
    end
```

**Comment by r-icarus** [comment]
I thought about copying the admin_routes code but I thought it was good to ask first. Thanks!

**Comment by smpallen99** [comment]
Actually, don't bother. Just pushed an update that supports using your own pipeline. After you update the dep, try this in your  router  `admin_routes pipeline: :browser`, then you add what ever you want in that pipeline.
