### ISSUE TITLE
Unique Constraint Issue.

### ISSUE THREAD

**Issue by blisscs** [smpallen99/ex_admin#97]
It's not possible to detect unique_constraint validation and give a nice error.
I see in the code that we check for valid? before doing insert or update.
And I see that when we do insert or update we presume that it's always success.
Probably by doing we miss the case when people has a unique_index and unqiue_constraint validation on the model. 

In web/controllers/admin_controller.ex
```elixir
if changeset.valid? do
          resource = ExAdmin.Repo.insert(changeset)
          put_flash(conn, :notice, "#{base_name model} was successfully created.")
          |> redirect(to: get_route_path(resource, :show, Schema.get_id(resource)))
        else
          conn = put_flash(conn, :inline_error, changeset.errors)
          contents = do_form_view model, conn, changeset.changeset.data, params
          conn |> render("admin.html", html: contents, resource: resource, filters: nil, defn: defn)
        end
```

In lib/ex_admin/repo.ex
```elixir
def insert(%ExAdmin.Changeset{} = changeset) do
    {:ok, resource} = repo.insert changeset.changeset

    case ExAdmin.Schema.primary_key(resource) do
      nil -> resource
      key ->
        resource = repo.get(resource.__struct__, Map.get(resource, key))

        for {cs, fun} <- changeset.dependents do
          if cs do
            fun.(resource, repo.insert!(cs))
          else
            fun.(resource)
          end
        end
        resource
    end
  end
``` 

I think we might need to adapt the code so that we don't check valid? and we just do insert or update and handle the errors if they arose from there.

**Comment by smpallen99** [comment]
Yes, changeset validation appears to be broken.

**Comment by smpallen99** [comment]
Constraint errors don't get recoginized until the Repo action is called. Changed the logic in the controller to handle the error correctly. Also add code to merge the constraint failures into errors for proper display of the errors.
