### ISSUE TITLE
Adding stylesheets to head

### ISSUE THREAD

**Issue by bsidoruk** [smpallen99/ex_admin#99]
Because Ex Admin is using it's own layout for rendering the admin pages, I am unable to include a stylesheet link in the page head. 
Such as:
```html
<link href='https://www.examplesite.com/example.css' rel='stylesheet' />
```
I was wondering if there was a way that I could inject a stylesheet link into the page head or otherwise edit the page layout template.

**Comment by smpallen99** [comment]
I need to add support for that. Great feature!! Hope to get to it soon.

**Comment by bsidoruk** [comment]
Thanks. That would be awesome.

**Comment by smpallen99** [comment]
The docs ...

  ## Adding Custom CSS or JS to the Layout Head

  A configuration item is available to add your own CSS or JS files
  to the `<head>` section of ExAdmin's layout file.

  Add the following to your project's `config/config.exs` file:

    config :ex_admin,
      head_template: {ExAdminDemo.AdminView, "admin_layout.html"}

  Where:
  * `ExAdminDemo.AdminView` is a view in your project
  * `admin_layout.html` is a template in `web/templates/admin` directory

  For example:

      # file web/templates/admin/admin_layout.html.eex
      <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin_custom.css") %>">

      # file priv/static/css/admin_custom.css
      .foo {
        color: green !important;
        font-weight: 600;
      }

**Comment by smpallen99** [comment]
@bsidoruk Hope that works for you...

**Comment by bsidoruk** [comment]
That's great, thank you!

**Comment by sstern6** [comment]
@smpallen99 might consider updating the docs.  It seems like the only way I can render admin_layout is if I name it `admin_layout.html.eex`, the docs specify `admin_layout.html`.  Not sure if it was something on my end or a new version of phoenix but thought I would mention this.

Thanks
